### ISSUE TITLE
CSS basic virtual scroller: when to relock?

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#100]
So if we use the css render-subtree, and we have all activations enabled (including viewport with what is currently implemented as a 50% margin), and I'm implementing a type of a virtual scroller... Then I'm listening to activation signals and recording what's visible. Then, at some point, I should make those items invisible again by resetting render subtree state (resetSubtreeRendered). 

But the question is when. How do I know I won't fight with the UA for viewport activation? 50% is a magic number in our case, so I really don't know when is the best time to hide the element again.

Furthermore, exposing whether element is rendered doesn't really help, because it would say "true". What we really want to expose here is "if I were to reset subtree rendered state, would the element become invisible?" and that's a really awkward function.

What can we do here?

/cc @chrishtr @rakina

**Comment by rakina** [comment]
If we spec the 50% part (or some other value we decide on), the author can just check that. Does that solve the problem? Or will that be more complicated? (I don't know how to actually check that :D)

**Comment by rakina** [comment]
also cc @fergald

**Comment by vmpstr** [comment]
@bgirard suggested that perhaps we can have an opt-in behavior that allows UA to relock the element when it exits the activation region. It's unclear whether this would be the case for all activations or just visibility, or how we can surface this behavior (another token? heh)

/cc @fullstackhacker

**Comment by vmpstr** [comment]
> If we spec the 50% part (or some other value we decide on), the author can just check that. Does that solve the problem? Or will that still be complicated? (I don't know how to actually check that :D)

I feel like we shouldn't really spec the 50% part, which is why this is a problem.. It's a bit of a magic heuristic. Presumably if UAs can render content faster, then they can have smaller activation windows. Since this is just for visibility, I don't think there's any compat issues since it's still dependent on user scrolls

**Comment by chrishtr** [comment]
> @bgirard suggested that perhaps we can have an opt-in behavior that allows UA to relock the element when it exits the activation region. It's unclear whether this would be the case for all activations or just visibility, or how we can surface this behavior (another token? heh)

If we do it then I think it should be the default. This way there is a mechanism for a site to have default-good performance with no script. All they have to do is add `rendersubtree` to turn on the required containment + placeholder sizing features.

However, we would then have to define what happens if you specify `invisible for `rendersubtree` but no placeholder sizing. We could have an arbitrary default, similar to the default sizing for iframes, that could be overriden by an explicit value. And even when re-locked use the previous layout size if available to refine the default.

**Comment by fergald** [comment]
I feel like anyone who wants to actively control visibility based on
scrolling should control it fully, that is, disable scroll activation and
do it themselves. It may be that we could have some better primitives for
doing this nicely, e.g. an IntersectionObserver mode that is for "I want to
efficiently observe all the children of this node" and maybe have that only
work if the children fit some constraints (basically exactly the same as
scroll activation). That way the author doesn't need to know the magic
numbers, doesn't need to manually observe a bunch of things etc.

>

**Comment by chrishtr** [comment]
Also: if the user agent re-locks, then we might need a `beforedeactivate` event to allow script to observe it. One use case is so that the page applies changes that cause the content to not affect outer layout (see [here](https://github.com/WICG/display-locking/issues/81#issuecomment-566287722)).

With an attribute-based `rendersubtree` this particular use case does not need an event, since attribute selectors can automatically apply CSS when content is invisible. With the CSS version it does need the event.

**Comment by vmpstr** [comment]
Just to get a pulse on this, is the sense that it's a good idea for the UA to be relocking or no? :) If so, we can dive in and try and figure out all of the edge cases and exactly when relocks happen. If not, then we need another way to figure out when to relock things (the initial question).

The pros of UA locks are:
  * simple to use
  * 'set it and forget it' semantics for the rendersubtree attribute
  * consistent sizing with content-size aware intrinsic size

The cons:
  * might not be obvious when this triggers (ie what if find-in-page activate match is in the content; what if script called focus() and then user scrolled away, etc)
  * doesn't provide developers with knowledge of when to relock (if devs want to do it themselves)

**Comment by chrishtr** [comment]
> Just to get a pulse on this, is the sense that it's a good idea for the UA to be relocking or no? :)

I think it's a good idea. That way the API's performance does not degrade by default after scrolling around, and adoption is very easy.

To put it another way, if the user agent automatically re-locks by default, then the user agent has now provided a certain version of virtual content for free.

**Comment by fergald** [comment]
Useful combinations
1 auto unlocking - improves initial render time
2 auto unlocking and relocking - improves initial render time and prevents degradation after scrolling around
3 disable scroll-based auto-anything - makes virtual scrollers easy to implement and we believe that there are reasons for virtual scrollers to exist that we will not try to solve in-browser.

From my perspective I don't mind which of 1 and 2 you do, as long as 3 remains possible.

**Comment by vmpstr** [comment]
I think we've settled on viewport activation doing 2, and 3 will still be possible by disabiling viewport activation.
