### ISSUE TITLE
CSS render-subtree: should containment apply if not invisible?

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#104]
Hi,

It is technically valid to have `render-subtree: skip-viewport-activation` without the invisible token (same with `skip-activation` or really any non-empty valid token that does not include `invisible`).

This means that (in our current thinking) this has no effect on rendering. Things are still rendered as before, signals aren't sent, etc, etc. One other consequence of this is that we don't tack on layout and style containment. Should we? FWIW for the attribute version, the mere presence of the attribute is enough for us to put in layout and style containment, so perhaps the answer is obvious here.

**Comment by vmpstr** [comment]
Also, and this is most certainly a bug (both in chromium and in the spec?), if we have render-subtree: invisible CSS property that activates, we still have size containment present.

This falls out of the tentative spec says something along the lines of 'if invisible token is present, then size containment is enforced'. It should probably call out the case of auto activation (or being activated).

**Comment by rakina** [comment]
I thought the reasoning for containment to apply even when not invisible (but the attribute is present) is so that the style will be consistent when locked vs unlocked?

**Comment by vmpstr** [comment]
I agree with the layout + style parts. But the size containment was really there because we don't know how to size the element otherwise. In order to support responsive design or take good advantage of placeholder sizing, size containment has to only apply when actually invisible (ie invisible and not activated)

**Comment by flackr** [comment]
I could see this going either way. If the content is not actually being hidden there's technically not really a requirement for containment and no new behavior is being activated.

Enforcing containment reduces the layout delta if you're switching between render-subtree values that include / don't include hidden. However, I'm not sure what meaning there is in setting skip-* without a hidden token (since as you mentioned it has no effect).

**Comment by chrishtr** [comment]
I think it's ok to not have it affect rendering at all, especially considering future use cases like `skip-upgrades` and `skip-loads`, which really don't have anything to do with layout.

We previously proposed adding `will-change: render-subtree` as a way to cause style and layout containment, but that also conflicts with my comments about future use cases.

Maybe we should just advise developers to add style and layout containment?

**Comment by vmpstr** [comment]
That's fair. I'm going to close this, since I think the overall sense is that if we want style+layout to apply without the invisible token, then there should be some other way of doing it (either just put contain: style layout; or some will-change token).

**Comment by rakina** [comment]
So the conclusion is we keep style & layout containment anyways but not size containment?

**Comment by vmpstr** [comment]
My understanding is that contain: style and layout only apply if invisible token is present. Additionally size applies if the element is not activated (ie it's not actually rendered).

If we want style and layout to apply without the invisible token, then it's what chris suggested: either add will-change: render-subtree feature to do this, or just ask the developers to put the containment

**Comment by chrishtr** [comment]
Also, UA activation will not change whether the invisible token is present on the `render-subtree` css property, so UA activation will never cause a change to `contain: style layout`.

**Comment by fergald** [comment]
I'm not reopening this but I just want to make sure you've considered
whether there could be other non-empty states in the future where
containment is dropped? It seems like a bad idea to have it be non-obvious
whether containment is on or not. Empty vs non-empty makes it very obvious.
Do we actually gain anything by having a non-empty value that doesn't imply
containment?

>

**Comment by vmpstr** [comment]
Currently this is the state:

For attributes:
- The presence of an attribute is enough for us to add `contain: style layout`
- If, in addition, an `invisible` token is present, then we also add `contain: size`

I think we agree that this is a good state. For CSS, it's a bit different:

For css:
- The presence of render-subtree *with* `invisible` token is enough to add `contain: style layout`
- If, in addition, the element's subtree *is actually* invisible, then add `contain: size`

I'm happy to change this, as long as we maintain the part that says 'if *actually* invisible, then add size containment', since CSS doesn't remove the token when activating.

I'm going to re-open just so it's clear that this is still under discussion.

**Comment by fergald** [comment]
I don't think I agree with the first one. My way of thinking is:

1 does the choice make a difference right now? I think the answer is "no" and we can choose not-empty => `contain: style layout size` and nothing breaks and nothing is strongly one way or the other.
2 does one of the choices lead to regret? It seems to me that if we don't want a situation where people need to read docs or look up a table to figure out what the final containment is, we shouldn't take step 1 down that path. This doesn't stop us doing it in the future if we really want to.

There could be counterpoints but if there aren't then it seems like non-empty => all three always is the simplest.

**Comment by vmpstr** [comment]
I think the `size` part is the thing that gives me pause here. In any kind of responsive design page, we do not want to limit the 'natural' size of the element. That is, however big the element wants to be given its contents. Size containment rains on that parade.

However, when we are not rendering the element (meaning that we might not even lay it out etc etc), we *do* want size containment to ensure that we're not relying on our descendants for sizing information. 

As an aside, this is why we're hoping to have that intrinsic sizing property that would apply only if size containment is present to still give a responsive-like feel to the element where its size is not necessarily that of an empty element. 

All in all, I strongly believe that size containment should apply if and only if the element is not rendered.

For layout and style containment, I don't have a strong preference so whatever makes sense and is simplest to explain is fine by me.

**Comment by chrishtr** [comment]
I think the rule that `render-subtree: invisible` causes style, layout, and if actually invisible size containment, is not hard to understand.

The other envisioned token values of render-subtree are either modifications to `invisible` or orthogonal rendering-related features (skipping network loads or custom element upgrades) that don't have anything to do with style, layout or sizing. In fact, adding containment there would likely harm adoption for site layouts that don't want that.

If we ever add something like `render-subtree: skip-animations` or something, then that token would also imply containment.

**Comment by fergald** [comment]
OK, thanks for explaining more. I still feel like there's something a bit
wonky here, that we're overloading this attribute by it being both the
on/off switch and the place that has options but I can't think of another
way of expressing it that seems worth the complication.
