### ISSUE TITLE
On skip-viewport-activation not activating and timing of things

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#106]
So in the latest proposal, we have it so that skip-viewport-activation doesn't activate at all, it simply issues a signal when an element is a target of an active match (in find-in-page case) or scrollIntoView or any of those algorithms.

Now, all (or most?) of those algorithms also scroll the element into view. However, we expect that script, in response to the event, would remove the render-subtree property and expose content, possibly causing the element's box to grow and content to move around. 

This means that as it stands, it is likely that the content that is scrolled into view in response to an algorithm is not the correct content after script has handled the activation (or whatever we name it) event. 

There are three options, as far as I see:
1. Do nothing, and this is fine.
2. Execute the event handlers synchronously when the element is targetted, update layout, and then scroll
3. Queue the event, yield and resume the algorithm on the next frame after script had a chance to run.

1 is, of course, the easiest.
2 is also fairly straight forward to implement, but it feels... wrong to run event handlers in the middle of some arbitrary algorithm
3 is likely breaking. That is, scrollIntoView() for example expects that we've scrolled the element into view when the function returns. If we're going to yield before the actual scrolling, it breaks this assumption.

Are there other alternatives?

/cc @chrishtr @rakina @fergald @flackr

**Comment by vmpstr** [comment]
Just as an addendum, even if we activate and render the element (as we do in the current implementation), script is likely to respond to the activation signal and change some style that may still change content sizes. In other words, this isn't necessarily a fallout of the latest proposal, but it certainly makes the problem more noticeable.

**Comment by chrishtr** [comment]
The algorithms that seem problematic are all the script-induced ones, like `element.focus()` and `element.scrollIntoView()`. With `skip-viewport-active` on, the developer is supposed to be managing activations themselves, not the user agent.

Therefore, it seems ok to have methods like `element.focus()` and `element.scrollIntoView()` do nothing for non-activated elements.

User agent algorithms such as find-in-page and anchor link navigation, on the other hand, seem to have no problem waiting for the activate event to fire before running the algorithm. If the activate didn't result in anything, then those algorithms should skip the element.

**Comment by vmpstr** [comment]
That's a really good point. I guess for script stuff we can issue the signal and just scroll to where 'we think it would be'? Or signal and do nothing?

For UA algos, yeah we can delay. We need to be careful here:
- If we find an active match in a locked subtree, we issue the signal and delay a frame.
- When we 'come back to it', which I guess would have post animation timing, we check to see if it's still locked
- If it's unlocked, then scroll to it and done.
- If locked, skip it and go to the next match (and repeat if there are more matches in the locked subtree? we might be delaying it indefinitely, so I think we need to maybe skip all matches under the locked root instead)

Is this all speccable?

**Comment by chrishtr** [comment]
> That's a really good point. I guess for script stuff we can issue the signal and just scroll to where 'we think it would be'? Or signal and do nothing?

I think we do the same as if there were no descendants to the element. That is how `render-subtree: invisible` is being modeled in terms of layout.

**Comment by fergald** [comment]
The sticky point here to me seems to be that scrollIntoView is sync, so
it's valid to write code like

```js
foo.scrollIntoView();
off = bar.scrollTop;
```
and expect that `off` will be correct. We shouldn't make devs worry about
whether that content is managed or not or lazy content can never be a
drop-in replacement. How does raf interact with things like `scrollTop`
that force a layout? If the scroller posted an raf task in
`scrollIntoView`, would it run before `scrollTop` is calculated?
