### ISSUE TITLE
Handle case of replacing element and subtree without interrupting animations

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#12]
Display locking currently handles the case of locking a subtree and modifying it, while displaying
(or not) the old pixels for the subtree.

It does not, however, handle the case of replacing an element and its subtree, without locking that
element in the meantime. Replacing a large amount of content seems a common situation, and
continuing any interactions and animations during the computation of layout for its replacement
is useful. For example, any ongoing video, image, scroll, or script-driven animations or input operations could continue unimpeded.

This can be achieved by adding a new mode to DisplayLocking. There will now be usage modes modes:

1. The existing mode: _Subtree update_
a. Lock an element currently in the DOM
b. Update its subtree to new state
c. Commit and unlock element

2. The new mode: _Element and subtree update_
a. Create a new element
b. Lock it
c. Insert it into the DOM as a sibiling of the original element
d. Update its style (including sizing and paint containment), and subtree to new state
e. Commit and unlock element
f. In unlock promise resolution, remove original element from the DOM

In mode 1, the locked element itself is not "locked for display", meaning its box decorations are displayed and updated as usual, and it participates in layout.

In mode 2, the locked element is actually locked, meaning its box decorations are not displayed and it does not participate in layout. Only in step 2f does a visual update occur in which the new element has an effect on display to the screen.

Note that step 2f will have a cost equal to the cost of re-computing layout with the original element removed from the DOM (but no other changes made). This is because step 2e cannot predict whether this will happen, and can only compute layout assuming the new element and subtree will be added to the DOM. In combination with containment isolation, however, this final layout should be fast. This is because step 2d requires sizing and paint containment to be specified.

**Comment by chrishtr** [comment]
Another note: mode 2 does not really require step 2d (paint containment, sizing) at all, since in this mode there is no such thing as the snapshotted old pixels. However, the cost of step 2f will be proportional to the time spent laying out the new state with the old element removed; this will be minimized if paint containment and sizing is present.

Also note that mode 2 is equivalent to asyncAppend (https://github.com/WICG/async-append/blob/master/EXPLAINER.md).

**Comment by chrishtr** [comment]
@sebmarkbage What do you think?

**Comment by sebmarkbage** [comment]
Nice! Looks good.

Would it be possible to have this work for removals too? E.g. in the unlock of the addition, re-acquire the lock and you could also lock the element that is already on screen (using mode 2). Then remove it while it still is visible on the screen. Then unlock both to do the swap.

asyncAppend had a kind of batching mechanism for coordinating unlocks for the same frame. Is that possible in this case?

**Comment by vmpstr** [comment]
Questions for mode 2:
- When we acquire the lock, do we call the callbacks and continuations even if the element has not beed inserted into the DOM yet?
- If so, I'm guessing we don't want to resolve the promise before the element is actually in the DOM and is laid out? This would effectively mean that the lock is "soft suspended" until we put it in the tree, which is when we'll start the processing and resolving the promise
