### ISSUE TITLE
[css-subtree-visibility-1] use of 'auto' for non-initial value is awkward

### ISSUE THREAD

**Issue by dbaron** [WICG/display-locking#126]
@kenchris and I are looking at [the CSS Subtree Visibility draft](https://wicg.github.io/display-locking/) as part of w3ctag/design-reviews#306.

One thing we noticed is that the use of `auto` as a non-initial value of a CSS property can be awkward.  While CSS has done this in a few cases before, it's far from optimal, and it seems likely to be better to come up with a more specific name for that `auto` behavior.

**Comment by vmpstr** [comment]
Our reasoning for this was that, as you say, there is precedent (in things like overflow) and it captures the semantic meaning of what we're trying to accomplish.

The other word here that we had was `managed` to indicate that the user-agent would manage the visibility...

More context, and the full discussion on the token naming is here: https://github.com/WICG/display-locking/issues/110#issuecomment-588309247

**Comment by tabatkins** [comment]
Yeah, the "match overflow's keyword pattern" was the big reason we went for "auto" there. I agree with you in general, but I think the nice concordance in keywords works pretty well.
