### ISSUE TITLE
[css-subtree-visibility-1] inconsistent values of containment used

### ISSUE THREAD

**Issue by dbaron** [WICG/display-locking#129]
I'm looking at [the CSS Subtree Visibility draft](https://wicg.github.io/display-locking/) as part of w3ctag/design-reviews#306.

Following the [property's values](https://wicg.github.io/display-locking/#subtree-visibility) through to the underlying definitions, it seems like:
* `auto` causes layout and style containment (although the use of the [has containment](https://wicg.github.io/display-locking/#has-containment) definition means that it's not particularly clear that it causes those containment values)
* `hidden` causes layout, paint, and style containment

It seems like `auto` should probably trigger the same values of containment as `hidden`.  And probably this should through a definition worded a bit differently than "has containment", which is written like a test of whether something does have containment rather than a way of causing it to do so.

**Comment by vmpstr** [comment]
Oops, I think paint containment was never supposed to be a part of this. I'll put up a PR with the changes.
