### ISSUE TITLE
Declarative version

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#13]
Display locking makes sense also in a declarative mode, as an async attribute on elements. Updates to the visual display of such elements would be done asynchronously to the rest of the page, and therefore may not present atomically with other content. However, content under a single async element would be presented atomically to the screen. Async rendering would only apply to elements with appropriate containment CSS.

The attribute could be rendering={async|sync|auto}, with auto being the default; this allows browsers to potentially skip rendering heuristically for elements with containment CSS that were not on-screen, and are predicted not to be on-screen soon (e.g. scrolled far below the viewport). This is analogous to the decoding attribute for <img> elements (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)

**Comment by chrishtr** [comment]
An async attribute could also be used in conjunction with the HTML parser, as a way of hinting which content is most important to present to the screen first, and the grouping of content to be presented atomically. For example, a news article page which had the main article, together with some ads and snippets of other news, could put the ads and news in async elements, leading the browser to show the article before other content. The other content could also use the imperative display locking API to extend the length of the async period before rendering.

**Comment by chrishtr** [comment]
A `rendering=async` attribute can also be used to achieve the fragment link navigation use-case [Searchable Invisible DOM](https://github.com/rakina/searchable-invisible-dom). In this use-case, a document that is too large to render quickly in its entirety needs to be loaded anyway, and only the content on or near the screen should be rendered.

[invisible attribute method]
With the searchable-invisible APIs as described in its [explainer](https://github.com/rakina/searchable-invisible-dom), this use-case would be implemented by breaking the document up into chunks, and marking the root element of each chunk with an `invisible` attribute. The chunk that contained the anchor for the fragment navigation would be activated (rendered). In its `activateinvisible` event handler, script would remove the `invisible` attribute from nearby chunks sufficient to render one screen's content.

[rendering=async method]
An alternative implementation with a similar effect would be to put `rendering=async` on the root element of each chunk. The browser would then in general load the page and start rendering chunks
asynchronously in the background. Navigation to a particular fragment url within the document would
naturally offer an opportunity for the browser to render the chunk that contained the anchor for the fragment navigation. Script could listen for the [`beforecommit`](https://github.com/WICG/display-locking/issues/7#issuecomment-453203194) event and then remove the `rendering=async` attribute
on nearby chunks. Script would also, as desired, iterate over other elements with `rendering=async` on them and call `getDisplayLock().acquire()`.

**Comment by BoCupp-Microsoft** [comment]
Corner case to consider: rendering attribute can be removed while display lock is held. Not sure if we can guarantee appropriate usage of the API, which I think is what you're going for with the rendering attribute. Maybe we should fallback to sync style, layout, paint when we there's a loss of containment?

Disclaimer: just reviewed both the display locking proposal and CSS containment specs so let me know if I'm just misunderstanding the interactions.

**Comment by chrishtr** [comment]
@BoCupp-Microsoft Agreed that it should fall back to sync in this case.

**Comment by vmpstr** [comment]
rendersubtree!
