### ISSUE TITLE
Spec clarification: focus()

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#141]
This is a split off from #139 

In there, we decided that scrollIntoView() by existing spec interpretation, will first scroll into view and then rely on viewport intersection to render/paint the contents.

For focus(), [the spec](https://html.spec.whatwg.org/multipage/interaction.html#dom-focus) says that we first focus the element, then scroll it into view. Subtree visibility spec says that if 'auto', then the element is skipped only if neither it nor any of its subtree are focused.

So, following this it means:
1. We run focus steps
2. We start rendering/painting the element
3. We scroll into view.

The viewport intersection here is moot because the element is already focused. The question I have is if that interpretation makes sense. Steps 1 and 3 run right after each other, so presumably 2 is "instantaneous" in the fact that when we scroll and element into view, it already doesn't have size containment and uses whatever the non-size-contained size is to determine what to scroll.

Does that make sense? 

Alternative:
Step 2 above runs at "natural lifecycle" time so when we scroll, it is still size-contained, so we unlock (either due to viewport intersection or focus), but we scroll to the location as determined by the size-contained element.

@chrishtr Either way, I'd like to add some clarifying text in the spec, but which alternative do you think makes more sense here?

**Comment by chrishtr** [comment]
Focusing the element requires a synchronous style recalc I assume? 

I think the instantaneous interpretation makes sense. Because the scrollIntoView algorithm requires layout and therefore forces layout, and if focused elements are always not-skipped, and focus is instantaneous, then so is not-skipped.

**Comment by vmpstr** [comment]
Closed by #145
