### ISSUE TITLE
Align API shape with Web Locks?

### ISSUE THREAD

**Issue by inexorabletash** [WICG/display-locking#15]
For [Web Locks API](https://github.com/WICG/web-locks/) we ended up with somewhat different API shape to avoid explicit acquire/release in most cases:

```js
await navigator.locks.request('my_resource', async lock => {
  // callback is invoked once the lock is acquired
  await do_something();
  await do_something_else();
  // lock will be released when this async callback's implicit promise resolves
});
// the awaited request call's promise resolves once the lock is released
```

The promise returned by the `request()` function coul also reject if the lock request failed, timed out, or signaling other issues (e.g. if the lock was held for too long). 

We arrived at this API shape after much iteration (starting off with explicit acquire/release calls), and settled on it since it's "safe by default" (e.g. in the face of exceptions/returns, etc). The TAG went through the same iteration and ended up liking the approach.

In the display locking example, I could imagine an API shape like this:

```js
await element.requestDisplayLock(async lock => {
  // callback invoked once lock is held
  // Modify element's subtree. The DOM is modified immediately, same as without
  // display locking. However, rendering of the element is delayed.
  element.innerHTML = ...;
  // lock is implicitly released here
});
// awaited promise resolves once lock is released and UA finishes up with follow-up steps
```

Just throwing this out there to consider.

**Comment by vmpstr** [comment]
Oh interesting. So the main difference is really the fact that there is one call that a callback to call when the lock is acquired (without an explicit "acquire" promise), and the return value is the promise that is resolved when the work is finished. Is that correct?

We have a few cases where we do want to hold on to the lock without committing/releasing it immediately, which is where I think the design differs a little bit. However, I think we might want to discuss incorporating the idea of not having an explicit acquire (ie getting the display lock object calls a callback when it is acquired and passes the lock handle to the callback). Unfortunately this isn't "safe by default" as in the lock would still need to be explicitly released.

**Comment by inexorabletash** [comment]
> Is that correct?

Yes.

> We have a few cases where we do want to hold on to the lock without committing/releasing it immediately, which is where I think the design differs a little bit.

This is doable in the web locks API since the callback can return an arbitrary promise, and the lock is held until it resolves. In the extreme case, you can create a lock that is held for the lifetime of the execution context:

```js
// note lack of await/async below
let is_master = false;
navigator.locks.request('master_election_lock', callback => {
  // Yay, I was elected master.
  is_master = true;
  // Hold the lock until this execution context is terminated.
  return new Promise(resolve => { /* never */ });
});
```
The code here is not idiomatic - generally, if you need to type `Promise` these days it's a sign things are complicated - but it works.

Happy to brainstorm offline, too.

**Comment by jakearchibald** [comment]
The problem with the current API:

```js
async function updateDom() {
  const lock = document.body.getDisplayLock();
  await lock.acquire();
  thisFunctionSometimesThrows();
  lock.commit();
}
```

…the page may freeze. Whereas:

```js
function updateDom() {
  document.body.displayLock(async () => {
    thisFunctionSometimesThrows();
  });
}
```

…this doesn't.

**Comment by sebmarkbage** [comment]
Another consideration is that this might need other features like synchronous commit or rollback. #17 I think this should still be sufficient as long as there is a first class lock object passed into the function.

**Comment by vmpstr** [comment]
I definitely see the value of having safe-by-default API: the case of a throwing function is particularly compelling. However, I do think that we need a first class lock object since, I believe that it would be a common pattern to hold on to the lock for an extended period of time. On top of that, we can extend the lock API to include things like synchronous commit ( #17 ). 

Off the top of my head, I can't think of a nice and clean way of doing both (other than having two different ways of getting the lock, one safe by default, one explicit lock handle). I do think we need to think about this a bit more, and have a good justification for whatever we agree on.

**Comment by jakearchibald** [comment]
The lock object could be passed into the callback. There's also
`AbortController` - a signal could be passed in as an option.

**Comment by jakearchibald** [comment]
Lock object in callback:

```js
function updateDom() {
  document.body.displayLock(async (lock) => {
    someStuff();
    lock.syncCommit();
  });
}
```

Abort controller:

```js
function updateDom() {
  const controller = new AbortController();
  const { signal } = controller;

  document.body.displayLock({ signal }, async () => {
    someStuff();
    controller.abort(); // release the lock early
    someOtherStuff();
  });
}
```

The lock object in the callback seems better.

**Comment by vmpstr** [comment]
We've discussed things, and I think this is doable for the patterns that we've considered. Specifically, the current thought is to have a pattern like the following:

```
async function baz(context) {
  someStuff();
}

async function bar(context) {
 someStuff();
}

async function foo(context) {
  someStuff();
  context.schedule(bar);
}

function updateDom() {
  document.body.acquireDisplayLock(foo);
  document.body.acquireDisplayLock(baz);
}
```

foo() and baz() are both scheduled asynchronously and are called after the lock on body is acquired. Also, they both block commit. foo() schedules a call to bar(), thus extending the lock. When all three are finished, the lock is committed.

Alternatively (future thoughts here), one could have
```
var lock_handle;
async function bar(context) {
  ...
}
async function foo(context) {
  lock_handle = context.suspend();
}
...
lock_handle.resume(bar);
```

Here, foo is called after a lock is acquired on some element, and it suspends the context, meaning that the lock will not be committed until resume is called. This satisfies polyfilling the searchable invisible dom use-case. Additionally, although the requirement is that you must call resume on the lock handle, we can also ensure that a GC of the lock_handle object causes resumption.

The lock handle represents a commit blocker, so it doesn't block scheduling on the context; it only prevents commit. We can also have multiple commit blockers each of which must be resumed before commit happens.

Maybe suspend is not perfect wording here, but we can bikeshed about naming if the pattern in general seems OK.

**Comment by vmpstr** [comment]
We should also include some way to notify the caller that the lock has been rejected for whatever reason. I think I prefer to have a second optional callback which would be only invoked if there was an error. The alternative is that acquireDisplayLock returns a promise which succeeds when the callback is run I guess? I don't really like this idea since it's a bit awkward to deal with both a promise and an explicit callback.

**Comment by vmpstr** [comment]
Although weblocks does do this (promise return value that one can wait on or presumably it can be rejected).

**Comment by vmpstr** [comment]
A couple of open questions:
- acquireDisplayLock returns a promise. Is this promise resolved when the callback finishes? When display lock is acquired? Is the promise resolution delayed if the callback schedules a continuation via a context?

- If a callback throws, do we reject the promise?

**Comment by chrishtr** [comment]
Per offline discussion with Vlad, current thinking is:

> * acquireDisplayLock returns a promise. Is this promise resolved when the callback finishes? When display lock is acquired? Is the promise resolution delayed if the callback schedules a continuation via a context?

acquireDisplayLock returns a promise. This promise resolves with an undefined argument, after the callback and all continuations via .schedule(), recursively, finish, and "commit is done".

> * If a callback throws, do we reject the promise?

The promise rejects only if an exception was thrown by the callback arg to acquireDisplayLock or one of the continuation callbacks passed to a call to .schedule(), recursively. The argument to the rejection is an undefined object. Commit of rendering still occurs even upon promise rejection, and takes into account whatever DOM state is at that time, including any partially updated DOM state mutated via callbacks etc.

When is "commit done"? It is done after the callbacks and continuations finish and also the rendering lifecycle finishes its cooperative (or not cooperative, see #17 ) update, but *before* a frame is generated or any input events are processed which might start to affect the element's subtree.

If, during the promise resolution or rejection callback, acquireDisplayLock is called, the lock is considered re-acquired and display/input are not yet affected until the promise returned by the new call to acquireDisplayLock is resolved or rejected.
