### ISSUE TITLE
Should `beforematch` work with closed `<details>`?

### ISSUE THREAD

**Issue by tomayac** [WICG/display-locking#162]
I tried `beforematch` with both the browser's find on page feature as well as a text fragment URL, but I couldn't get it to work with *closed* `<details>` elements. Is this (IMHO essential use case) supposed to work? Here's a [demo](https://beforematch-demo.glitch.me/#:~:text=lorem) (note the text fragment URL). It worked as intended once I `open`ed the `<details>`, but this feels semantically wrong.

**Comment by vmpstr** [comment]
As the implementation stands right now, this event would only fire on things that can already be found using either find-in-page or text fragment URL. Specifically in closed `<details>` element, neither of those algorithms can find the text and so `beforematch` is not fired.

That being said, I agree with you that it is one of the compelling cases for us to work on. In particular, we should fire the event and if the section remains collapsed (ie `beforematch` event handler does not expand the details section) then we continue on to the next search. However, if script does expand the section revealing the match then we can use that. This is very similar to our targetted use case of `content-visibility` (which is also being developed in tandem)

@chrishtr @josepharhar wdyt?

**Comment by chrishtr** [comment]
> As the implementation stands right now, this event would only fire on things that can already be found using either find-in-page or text fragment URL. Specifically in closed `<details>` element, neither of those algorithms can find the text and so `beforematch` is not fired.

How about having the UA automatically open an <details> element when text within it has find-in-page matching? The developer would opt out of this via `content-visibility: hidden`.

**Comment by josepharhar** [comment]
> How about having the UA automatically open a <details> element when text within it has find-in-page matching? The developer would opt out of this via content-visibility: hidden.

Nice idea! I was also thinking we could change `<details>` to just have `content-visibility: hidden-matchable`. Either way, we would be changing the way `<details>` works though... I wonder if we could do either of these without breaking and edge use cases...

**Comment by vmpstr** [comment]
I'm not sure about opening it automatically. I think that runs the risk of being web breaking in some cases. The opt-out is nice, but I would generally prefer an opt-in (ie have a beforematch handler). 

The other justification I have is that in order to be consistent with hidden-matchable, it would be just searchable and fire an event (in the same way as hidden-matchable works). 

That being said, having it automatically be searchable with a beforematch event sounds pretty good to me.

**Comment by tomayac** [comment]
I definitely think this use case needs to be supported. At the same time, I'm opposed to adding too much magic like opening `<details>` automatically. If this is desired, the author can do so themselves programmatically. The cool thing about the `beforematch` event is that the author can apply their own logic, like debounce the event, set a custom minimum search string length, or even limit certain areas from being searched by setting dynamic filters through additional UI.

**Comment by josepharhar** [comment]
> I definitely think this use case needs to be supported. At the same time, I'm opposed to adding too much magic like opening `<details>` automatically. If this is desired, the author can do so themselves programmatically. The cool thing about the beforematch event is that the author can apply their own logic, like debounce the event, set a custom minimum search string length, or even limit certain areas from being searched by setting dynamic filters through additional UI.

I agree, this makes a lot of sense. I just talked with @vmpstr and we agreed that it would be best to fire the beforematch event on the collapsed content inside `<details>` without opening it automatically. This will make it work just like `content-visibility: hidden-matchable`, but without the need to actually specify that property for `<details>` elements, and will not change the current default behavior.

**Comment by josepharhar** [comment]
I will keep this open to track the work to dig into `<details>` and find a way to fire beforematch on collapsed content.

**Comment by chrishtr** [comment]
SGTM!

> I will keep this open to track the work to dig into `<details>` ..

Pun intended? :)

**Comment by josepharhar** [comment]
`<details>` shouldn't need `beforematch` because it already has the `toggle` event
