### ISSUE TITLE
Fix beforematch scrolling

### ISSUE THREAD

**Issue by josepharhar** [WICG/display-locking#166]
https://accordion-display-locking.firebaseapp.com/

When find-in-page searching for "sea", the content unlocks but we dont quite scroll all the way to the matching text.

**Comment by josepharhar** [comment]
Some more feedback:

When searching for "che" the page doesn't quite scroll to the right spot. I think it's because the scroll area is expanded after we already tried to scroll to the match and hit the bottom of the page.

When searching for "ch" -- this toggles between Sections 2 and 3 based on the text inside them but does not always highlight the intended target.

**Comment by vmpstr** [comment]
I'm closing this since it seems to affect Chromium's implementation not necessarily the spec. The implementation is tracked in crbug.com/1087536.
