### ISSUE TITLE
[Bikeshedding] Display Locking is a confusing name

### ISSUE THREAD

**Issue by tomayac** [WICG/display-locking#170]
In conversations with developers, *Display Locking* repeated got confused with *Screen Wake Lock*, since *display* is a synonym for *screen*, at least in a broader sense. Can we find a better name for this effort? *Render Blocking* might be similarly confusing in the sense of render-blocking resources.

**Comment by vmpstr** [comment]
That's fair, although I think it might be pretty hard to find a name that avoids name collision with other features. FWIW, display-locking is currently a set of features that we're working on, so the project itself is not really exposed to developers other than a shortcut term for the set of features being worked on.

In conversations, we typically refer to `content-visibility` for the particular CSS feature that is exposed to developers to control rendering. There's also `beforematch` event and `content-visibility: hidden-matchable` which talks about another aspect of this project.

**Comment by tomayac** [comment]
I fully get it’s an umbrella term. How about simply calling it *Content Visibility/Findability* then?

**Comment by vmpstr** [comment]
I think that in general we do use content visibility or hidden-matchable depending on which aspect of the feature we're talking about. Unfortunately the fact that display-locking is used in conversations and in reference to this feature is hard to change. We're at the stage where we are close to shipping content-visibility in Chromium and essentially deprecating the use of the "display locking" wording, so I'm not sure what else we can do at this time.

We can change the readme to not say display locking, although that might confuse people who already are used to calling it that...

Any others suggestions are definitely welcome

**Comment by tomayac** [comment]
One other idea might simply be to add a "Not to be confused with Screen Wake Lock" note at the beginning of the README.

Naming and cache invalidation…

**Comment by vmpstr** [comment]
Good idea, I'll do that

> Naming and cache invalidation…
 
😃
