### ISSUE TITLE
Tab order / find in page

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#18]
Not sure if it's an issue or not, but would be nice to get some feedback: If an element is locked for display, but the DOM is modified in a way that the next tab order is in the locked subtree, then should it skip that element and go to the next tab order element that is unlocked?

Same question for find in page, should that find a thing that is currently locked or should it skip it?

**Comment by chrishtr** [comment]
For find in page: I think we need to skip the subtree, because there is no way to show the find-in-page UI anyway for the content. Find in page is a use case that could justify force-unlocking after a timeout (see also #20 ).

However, for "mode 2 from #12), the DOM which is going to be replaced can be found, because it is not locked.

**Comment by chrishtr** [comment]
Tab order has the same answer.

**Comment by ojanvafai** [comment]
The answer to this partially depends on how this feature will related to invisible DOM as invisible DOM will definitely want tab order / find in page to find locked subtrees and give the author the opportunity to unlock it.

I also think this depends on if there is a mode that shows stale pixels. If there isn't then there's no concern, but if there is, then you can have text that is displayed to the user, but doesn't get highlighted by find-in-page.

**Comment by ojanvafai** [comment]
Unlocking and relocking means that all that content would get rendered, right? That would be too expensive for a virtual scroller that has a lot of virtual content (a fairly common case).

I think there is probably a solution here that works for all use cases if think carefully about the event we want to expose for invisible DOM. I think that needs higher bandwidth discussion though, so set's chat offline and circle back here afterwards?

**Comment by chrishtr** [comment]
> Unlocking and relocking means that all that content would get rendered, right? That would be too expensive for a virtual scroller that has a lot of virtual content (a fairly common case).

Within the internals of the browser, unlocking does not have to mean all rendering. For example, if a user agent find-in-page is in progress and it just needs to see if text matches, just style could be computed.

Or if script wants to do something similar, such as examining all text nodes and checking for display:none subtrees, it could do it while content was locked by traversing the DOM and checking computed styles for display:none. The latter would cause a forced style update (see issue #21),
which has similar performance to the browser-internal use case above.

> I think there is probably a solution here that works for all use cases if think carefully about the event we want to expose for invisible DOM. I think that needs higher bandwidth discussion though, so set's chat offline and circle back here afterwards?

Sure, happy to talk.
