### ISSUE TITLE
updateRendering: What happens with hidden descendants?

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#196]
In order to have good performance, it is desirable for us to have semantics which don’t pierce into descendant subtrees. Specifically, if we call `updateRendering` on an element which has a descendant element with `content-visibility: hidden`, the update would not recurse into the subtree, but rather consider that subtree to be updated.

**Comment by noahlemen** [comment]
> the update would not recurse into the subtree, but rather consider that subtree to be updated

I agree. Would this be true of any descendant element with containment, or only ones with `content-visibility:hidden`? I suppose a descendant with containment but without `content-visibility:hidden` would effectively be a no-op anyway?
