### ISSUE TITLE
Consider will-change: content-visibility as alternative to renderpriority.

### ISSUE THREAD

**Issue by flackr** [WICG/display-locking#211]
The explainer for renderpriority suggests that the use case is to prepare content which was hidden to be displayed. I'd like to suggest that we consider using `will-change: content-visibility` as a hint for this. will-change is an already established rendering hint which is currently used to tell the UA to prepare for elements to have mutations to transforms, opacity, etc, so it seems reasonable that `will-change: content-visibility` could be used as a hint for the UA to prepare for changes to content-visibility (i.e. update the rendering of the element).

**Comment by vmpstr** [comment]
Let's continue the discussion in #200
