### ISSUE TITLE
Browser remembers `contain-intrinsic-size`s that don't match developer-specified size

### ISSUE THREAD

**Issue by josephrocca** [WICG/display-locking#215]
I've got a feed of posts for which I don't know the exact height - it depends on how the text wraps, and on the width of the screen, and on the user's system fonts.

This isn't tooo much of an issue in my cause (though it's certainly not ideal), since I just set an approximate height. The main reason I use this feature is to make page load faster.

But I've been wondering whether it'd be possible to have an option that tells the browser to remember the *actual* sizes of the elements as it comes across them, so that when the users scrolls back up the page, there's not a weird scroll bar resizing problem where they're not actually sure how close to the top they are. That problem is worse for the desktop users who tend to grab the scroll bar with their mouse to quickly move back to the top of a long page/feed - their mouse hits the top of their screen and they're only 80% of the way up, for example.

Is a feature like this feasible at all? Or is there some other approach that makes more sense for this sort of problem? I could certainly do it with JavaScript (probably using my own intersection observers?), but I'm worried about performance and complexity.

**Comment by chrishtr** [comment]
The `auto` keyword does what you are asking.

https://web.dev/content-visibility/#specifying-the-natural-size-of-an-element-with-contain-intrinsic-size

https://drafts.csswg.org/css-sizing-4/#last-remembered

**Comment by josephrocca** [comment]
\*Facepalm\* - thank you!
