### ISSUE TITLE
What is the story for polyfilling this API?

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#22]
For user agents which do not yet support Display Locking, what is a developer supposed to do as a fallback?

**Comment by vmpstr** [comment]
Good question. 

Jank is likely to be unavoidable in that case, but for the visual effect the dev would have to build up the subtree outside of the DOM and the insert it after all of the content is populated. Seems reasonable?

**Comment by vmpstr** [comment]
I think in rendersubtree, the dev can just use other methods of hiding content, albeit losing activatability. 

Some possible polyfills for this are listed in #62
