### ISSUE TITLE
Support full-framerate (e.g. 60fps) animations

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#26]
It should be possible to achieve full-framerate animations (i.e. ones that are cheap enough to run at that speed) using Display Locking, just as it is with requestAnimationFrame.

However, with current semantics this will result in an extra frame at the beginning of an animation, and an extra frame *between* animation frames.

Consider:

~~~~
1  function renderFrame() {
2  ...
3  requestAnimationFrame(renderFrame);
4 }
5  requestAnimationFrame(renderFrame);
~~~~

The browser attempts to run the [rendering event loop](https://github.com/chrishtr/rendering/blob/master/rendering-event-loop.md) at its desired framerate.
Step 6 of that loop is running requestAnimationFrame callbacks. If requestAnimationFrame is called from within such a callback, the argument to the requestAnimationFrame method is run at the *next* frame. Therefore this code will execute the `renderFrame` method at full-framerate, assuming the code and DOM update can fit within the frame deadline.

Now consider this example:

~~~~
function renderFrame() {
  ...
}

function acquire() {
  acquireDisplayLock(renderFrame).then(() => requestAnimationFrame(acquire));
}
~~~~

The promise resolution callback happens after all rendering work is done, but *before* committing to the screen. This is because the resolution callback needs to be able to re-lock the content
if desired, even after completion of all tasks, in order to support such use-cases as measuring layout.

In addition, the rendering loop must run once after calling acquireDisplayLock before calling its callback parameter, in order to set up the cached state that will be displayed while the element is locked.

Therefore the sequence of actions to go through two rounds of acquire/renderFrame is going to be:

1. acquireDisplayLock
2. Run rendering loop (to cache pixels for step 1)
3. Run renderFrame callback
4. Run rendering loop for first frame of animation (but not yet displayed!)
5. Run promise resolution callback.
6. Run rendering loop. This calls acquireDisplayLock in a rAF callback, then *renders content actually computed in step 4*. Also caches pixels from first frame.
7. Run renderFrame callback.
8. Run rendering loop  for second frame of animation (but not yet displayed!)
9. Run promise resolution callback.
10. Run rendering loop to display second frame.

Note that between steps 6 and 10 there are two rendering loops. This means that an acquireDisplayLock rendering loop cannot run faster than half the framerate of the device. This is undesireable.

One way to fix this is have a way to declare a display lock to be passive, e.g. by passing a parameter indicating such. Passive display locks would not allow script to abort in in the completion callback. This would allow us to display the second frame in step 8 rather than 10, because step 9 was not allowed to re-lock.

This would allow the animation to run at full-framerate, except for one additional frame at the start of the animation.

**Comment by vmpstr** [comment]
This makes sense to me. Thanks for a detailed summary

> One way to fix this is have a way to declare a display lock to be passive, e.g. by passing a parameter indicating such. Passive display locks would not allow script to abort in in the completion callback. This would allow us to display the second frame in step 8 rather than 10, because step 9 was not allowed to re-lock.

I'd say that rather than disallowing things to happen here, we can instead say that a call to acquireDisplayLock within the promise resolution of a passive lock acquires a new lock and the contents prepared by the existing lock are still displayed. In other words, this simply doesn't delay current contents but requests a new lock.

**Comment by chrishtr** [comment]
> I'd say that rather than disallowing things to happen here, we can instead say that a call to acquireDisplayLock within the promise resolution of a passive lock acquires a new lock and the contents prepared by the existing lock are still displayed. In other words, this simply doesn't delay current contents but requests a new lock.

Makes sense.

**Comment by vmpstr** [comment]
I don't think we're targeting this with rendersubtree. This seems more render=async territory. Re-open if you disagree
