### ISSUE TITLE
Mode 2: when to append the element

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#29]
Mode 2 (which I propose we call lock-before-append to avoid confusion) says that if we acquire the display lock before appending the element to the dom, then no pixels will be displayed for the element. They only appear after layout and whatnot have completed and the promise is resolved.

It is a bit unclear/ambiguous in this case what it means to have a display lock be acquired. Specifically, the promise that acquireDisplayLock returns resolves after the lock is committed (ie things have been laid out), so that can only happen if the element is already appended into the DOM.

So, consider this:
let e = document.createElement("div");
e.acquireDisplayLock(func1).then(func2);
func3();

So, when should "e" be placed into the DOM? It can't be func2() since that's that the completion callback and it doesn't run until we actually laid things out.

func3() also seems a bit suspect since acquireDisplayLock is meant to be asynchronous, so it looks weird although from the implementation perspective there's nothing wrong with doing it there. Ie, we already know that the lock was requested, so whether we append the element immediate after that or a bit later doesn't really matter.

func1() seems to also be an "ok" spot to do it, although it's now responsible not just for generating the content but also appending it to the DOM.

What should be the recommended guidance (I'm in the process of writing layout tests, and I'd like them to be canonical)

**Comment by chrishtr** [comment]
Maybe the canonical advice should beg to do it immediately after acquiring:

let attachPoint = document.querySelector("#attachPoint");
let e = document.createElement("div");
e.acquireDisplayLock(func1).then(func2);
attachPoint.appendChild(e);
func3();

It's only necessary I think to wait for acquireDisplayLock to be called before appending, and not have to wait for func1. func1 may be delayed, but we can pre-emptively mark e as async before that.

**Comment by vmpstr** [comment]
That makes sense to me. I think that's what I will mostly use in layout tests, with a few tests testing other non-canonical examples.

There's interesting lifetime implications when you do

let e = document.createElement("div");
e.acquireDisplayLock((context) => { document.body.appendChild(context.lockedElement); });

since the callback can be delayed and nothing other than the display lock context can keep |e| alive.
