### ISSUE TITLE
Dealing with CSS Animations.

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#3]
We need to figure out what to do with CSS animations in a locked subtree. The current plan of record is to suspend all animations in a subtree. This would also have to include things like pausing animated GIFs.

**Comment by vmpstr** [comment]
This still needs some discussions. rendersubtree=invisible and then triggering an animation, and in transitionend saying rendersubtree=visible. Is that possible? Or will animation/transition events not fire for the subtree?

**Comment by chrishtr** [comment]
I don't think animations targeted at an element under rendersubtree=invisible should run, and therefore neither should animation lifecycle events.

**Comment by vmpstr** [comment]
We should add tests for this.
