### ISSUE TITLE
Observation pattern for lock lifecycle

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#36]
It seems useful to provide lifecycle observation events for locks. This allows code that is not directly
manipulating the lock to observe its state transitions.

beforecommit: event fired during the [rendering event loop](https://github.com/chrishtr/rendering/blob/master/rendering-event-loop.md) but before step 7.

This is an opportunity for script to do additional work that should happen at the same time as the commit.

didcommit: event fired after step 7 completes

This allows script to run immediately after commit but before any other event loop tasks.

**Comment by chrishtr** [comment]
These events would be fired on the DisplayLock object.

**Comment by vmpstr** [comment]
hey this is now possible with mutation observer and rendersubtree! :D

**Comment by chrishtr** [comment]
\o/
