### ISSUE TITLE
Use case: post-rendering callback. Relation to Display Locking?

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#37]
A use case not satisfied by any web API at present is a post-rendering callback. This is a callback
that happens after rendering occurs, and at which it is guaranteed that layout is clean. Therefore
it is performant to query layout-inducing DOM APIs such as offsetTop, or style-inducing ones
such as getComputedStyle().

Since there is no such API on the web, there is no way to in general write script that queries style-
or layout-inducing properties and is guaranteed not to force style or layout.

In the presence of Display Locking (DL), this concept starts to break down. In particular, style and layout are not actually clean for locked elements and their subtrees.

Therefore it seems that post-rendering callbacks should be tied to the concept of a Display Lock. Display Locks are in turn a way to model and control rendering for specific parts of a page. For the entire page, the built-in rendering event loop processing model of the browser can be modeled like this:

```
// This code runs before rendering of the page begins:
let rootElementLock = document.documentElement.getDisplayLock();
// This is the well-known event loop of the browser.
rootElementLock.acquire(() => {
  // commit synchronously and immediately re-acquire the lock. This models the way that
  // script writing to DOM does not cause rendering until a yield and commit begins.
  rootElementLock.commit(() => rootElementLock.acquire());
});
```
Thought about this way, for a page with no additional DLs, the natural way for script to register a post-rendering callback would be to observe the commit resolution of rootElementLock. This could be achieved with a lifecycle observer for didcommit on rootElementLock (see #36):

```
document.documentElement..getDisplayLock().addEventListener("didcommit", () => { ... });
```

**Comment by vmpstr** [comment]
I think this hinges on what post rendering callback promises. I don't think it can ever guarantee that layout is clean, since that completely eliminates any heuristics for far off-screen contained content (or display locked content) skipping work.

I think the best it can promise is that if nothing else changes, the UA is not going to do any more work. This is consistent with rendersubtree locked elements. 

Or do you believe that we should actually have clean layout before calling any such callback?

**Comment by chrishtr** [comment]
I think this is obsoleted by the following:

https://github.com/WICG/requestPostAnimationFrame/blob/master/explainer.md
