### ISSUE TITLE
Behavior of DisplayLockContext methods in corner case situations

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#38]
1. Call commit on an un-acquired lock.

=> Does not reject. Resolves after next render.

2. Call commit on acquired lock, in the middle of update().

=> Does not reject. Upgrades to commit, finishes on next render, and commits immediately after.

3. Call update on an un-acquired lock.

=> Equivalent to calling commit() on an un-acquired lock.

[Rationale: use case is a developer wanting
to unlock the element, and would like to use cooperative commit if possible, but if the lock is not acquired
we might as well commit, because acquire() costs the same as commit() in this case]

4. Call to acquire() when already acquired.

=> Immediately resolves.

5. Call to commit() after commit() but before commit is finished.

Resolves at same time as other commit().

6. Call to update() after commit() but before commit is finished.

Equivalent to item 5.

7. Call to acquire() after commit() but before commit is finished.

Resolves at same time as commit().

8. Call to acquire() during commit resolution callback.

Resolves immediately.

[See https://github.com/WICG/display-locking/issues/26#issuecomment-453201521]

9. Call to update() after update() but before other update() is finished.

Resolves at same time as other update().

10. Call to commit after update() but before other update() is finished.

Upgrades to commit and rejects other update.

[Rationale: the other update might have been measuring pre-commit layout, which is no longer possible if we upgrade to commit.]

11. Element style changes to not be compatible with Display Locking.

=> Equivalent to calling commit()

**Comment by vmpstr** [comment]
> 3. Call update on an un-acquired lock.
> 
> => Equivalent to calling commit() on an un-acquired lock.
> 
> [Rationale: use case is a developer wanting
> to unlock the element, and would like to use cooperative commit if possible, but if the lock is not acquired
> we might as well commit, because acquire() costs the same as commit() in this case]

I'm not sure I agree with this one. With a locked element, a call to update does not result in an element being unlocked. It seems inconsistent that there is an exception that says "unless the lock is in the process of being acquired".

The cases are:
- unlocked element -> update() rejects and no action is taken, element is unlocked
- locked element -> update() eventually succeeds and the element is still locked

The two possibilities are:
- pending locked element -> update() rejects and the lock is eventually acquired
- pending locked element -> update() causes a commit(), succeeds, and the element is unlocked

I can see the developer changing their mind and wanting an immediate unlock, but that can be done with commit(). I don't think calling update() before the lock is acquired has valid use cases.

We could write something like
acquire();
update().then(() => commit(), () => commit()) meaning both promise resolution and rejection commit the lock. Is this the usecase you're thinking of?

> 7. Call to acquire() after commit() but before commit is finished.
> 
> Resolves at same time as commit().

Do you mean something like:
commit() -> starts commit
acquire() -> commit is still pending, so this is "promoted" to pending acquire which causes a clean lifecycle up to paint, but does not paint. 

Or is it desired to have a frame with commited content visible before re-acquiring and clearing the output?



> 10. Call to commit after update() but before other update() is finished.
> 
> Upgrades to commit and rejects other update.
> 
> [Rationale: the other update might have been measuring pre-commit layout, which is no longer possible if we upgrade to commit.]

The update rejects here?
ie update(); commit(); then commit succeeds and update rejects; am i understanding that correctly?

> 11. Element style changes to not be compatible with Display Locking.
> 
> => Equivalent to calling commit()

Hmm we might not know this if we're locked. At what point do we check? During an update()?

**Comment by chrishtr** [comment]
> I'm not sure I agree with this one. With a locked element, a call to update does not result in an element being unlocked. It seems inconsistent that there is an exception that says "unless the lock is in the process of being acquired".
> 
> The cases are:
> 
> * unlocked element -> update() rejects and no action is taken, element is unlocked
> * locked element -> update() eventually succeeds and the element is still locked
> 
> The two possibilities are:
> 
> * pending locked element -> update() rejects and the lock is eventually acquired
> * pending locked element -> update() causes a commit(), succeeds, and the element is unlocked
> 
> I can see the developer changing their mind and wanting an immediate unlock, but that can be done with commit(). I don't think calling update() before the lock is acquired has valid use cases.
> 
> We could write something like
> acquire();
> update().then(() => commit(), () => commit()) meaning both promise resolution and rejection commit the lock. Is this the usecase you're thinking of?

The use case I'm thinking of is that the developer wants to unlock, but doesn't mind it taking multiple frames. But if there is going to be an acquire()-induced render happening anyway, then what's the point of that delay? It should unlock in one frame.

Since the DisplayLockContext cannot currently be inspected, if the behavior I'm suggesting is not done, the best the developer can do is:

let wantsToUnlock = false;
lock.acquire().then(() => { if (wantsToUnlock) commit(); }
if (oopsIDon'tWantToLock())
  wantsToUnlock = true;

If we add updateAndCommit (also desired for 60fps use-case, #26) then my suggested semantics
could apply to updateAndCommit only, and update() could still throw. SGTY?

**Comment by chrishtr** [comment]
The other reason that using updateAndCommit would be convenient is that the developer could just
use a more universal and fool-proof pattern when unlocking: just call unlockAndCommit, and no matter what it'll be fast and as performant as it can be.

**Comment by chrishtr** [comment]
> > 1. Call to acquire() after commit() but before commit is finished.
> > 
> > Resolves at same time as commit().
> 
> Do you mean something like:
> commit() -> starts commit
> acquire() -> commit is still pending, so this is "promoted" to pending acquire which causes a clean lifecycle up to paint, but does not paint.
> 
> Or is it desired to have a frame with commited content visible before re-acquiring and clearing the output?

The latter. The commit is not aborted. It's equivalent to calling acquire() during the Promise resolution of commit.

**Comment by chrishtr** [comment]
> The update rejects here?
> ie update(); commit(); then commit succeeds and update rejects; am i understanding that correctly?

Yes. I wrote it confusingly, but that is what I meant.

**Comment by chrishtr** [comment]
> Hmm we might not know this if we're locked. At what point do we check? During an update()?

At what point do we check style? I was assuming in a styleDidChange callback for the locked element. WDYT?

**Comment by vmpstr** [comment]
> let wantsToUnlock = false;
> lock.acquire().then(() => { if (wantsToUnlock) commit(); }
> if (oopsIDon'tWantToLock())
> wantsToUnlock = true;

For this one, you can do the following:
lock.acquire();
...
if (oopsIDon'tWantToLock())
  lock.commit();

which would work... I just have a problem with

if (oopsIDon'tWantToLock())
  lock.update();

doing the same thing, since it would only be the same if the lock is still pending, you really then want

if (oopsIDon'tWantToLock())
  lock.update().then(() => lock.commit());

which may or may not update and may or may not call commit, depending on the current state of the lock.

However, I do like updateAndCommit() which I think is much easier to reason about and should unlock whether or not the lock has been already acquired. If it has been, then it will also update.

I guess it's somewhat similar but I think it's cleaner.

**Comment by chrishtr** [comment]
Other than clarifying desired behavior in some corner cases, I think we have discovered the
following:

update() makes no sense unless the lock is acquired. Therefore we should try to not even expose
it on a object available when the object is not locked?

updateAndCommit() makes sense. Let's add it.

**Comment by fergald** [comment]
One more case that I think is not covered:

- call acquire but before acquire resolves, call commit

It seems correct to reject the acquire promise since the acquire did fail. It also seems reasonable to do this, e.g. you lock a bunch of things to hide them and avoid rendering cost but then in RAF you know which ones you want to show, so you commit those.

So the problem here is that this is not an error and it should be easy to distinguish this type of intentional "failure" to acquire from an actual failure to acquire but at the moment that involves checking

reason.message == "Lock commit was requested.

Comparing strings is not good. Is there an enum of failure reasons we can use?

**Comment by rakina** [comment]
Maybe for that case we shouldn't throw exceptions and instead just give a string reason? Other cases for rejection (containment is not satisfied, updating when not locked) are clearly "wrong" and makes sense for exceptions.

**Comment by fergald** [comment]
Checking against a human-readable string like "Lock commit was requested." means that snippet of English becomes part of our API and we cannot change it without risking breaking pages. Add some erro names specifically for display locking sounds reasonable. Another possibility is to use a different exception class (or hierarchy of classes) with more structure but that doesn't seem necessary.

**Comment by vmpstr** [comment]
Checking against strings is definitely not the right thing. However, I'm curious why we need to know what type of error this is? This is a promise rejection regardless of the error specified. Do you mean you want to have a set of "expected exceptions" and ignore those? I guess if every exception had a unique code, you'd be able to do that, but I'm not sure that's the accepted guidance

**Comment by fergald** [comment]
@vmpstr yes, there are legit ways of writing a page such that these would be "expected exceptions" and so you could imagine if you had set up remote error reporting, that you would want these to be treated differently to other failures to acquire/commit etc and you would not want to know about them in error reports.

**Comment by vmpstr** [comment]
I think this is mostly resolved and is somewhat outdated since we're switching to rendersubtree now.
