### ISSUE TITLE
Clarify that updates after commit() is called but before promise resolution are sync

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#40]
Consider the following code:

element.displayLock.acquire(() => {
  element.displayLock.commit();
  element.offsetLeft;
}

In this situation, offsetLeft left would use the committed offsetLeft of the layout of the element. OTOH:

element.displayLock.acquire(() => {
  element.offsetLeft;
}

Here offsetLeft would only be based on the intrinsic sizing of the element, not its surrounding context.

**Comment by vmpstr** [comment]
deprecated by rendersubtree
