### ISSUE TITLE
isLocked: attribute or function?

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#43]
From https://chromium-review.googlesource.com/c/chromium/src/+/1464202

We've added an isLocked attribute, but perhaps it should be a function to make it clear that it's not a settable attribute. Not sure what the best js style is here.

@domenic for an opinion.

**Comment by domenic** [comment]
Generally we use getters (i.e. `readonly attribute`s) for this sort of situation. Also, we omit the "is" (so just `locked`), but that's more loose. (See https://w3ctag.github.io/design-principles/#api-surface last paragraph.)
