### ISSUE TITLE
Extremely large content discussion

### ISSUE THREAD

**Issue by andyearnshaw** [WICG/display-locking#49]
All browsers have a maximum size (including scroll size) for elements, Chrome and Safari are 33.5 million pixels, Firefox is 17.5 million pixels, Edge is 1.5 million pixels. This makes virtual scrolling for lists and grids larger than that awkward, the way we are approaching it (in our list component) at the moment is using a sort of parallax to say, for example, 1 scrollable pixel is 5 virtual pixels, to get a scroll height of 5 * 33.5 million pixels in Chrome/Safari. The problem with this approach is that a single turn of the mouse wheel now scrolls way more pixels than we want it to. There are other things we can do to mitigate this to some extent but it would be nice to have a native way to solve this problem.

While [discussing](https://bugs.chromium.org/p/chromium/issues/detail?id=932109&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) this problem on the Chromium bug tracker, @chrishtr mentioned that display locking could potentially allow you to have a scroll bar that is not affected by this limitation.  I'm having a bit of difficulty seeing how this would work with the current draft and hoping someone could shed some light.

**Comment by chrishtr** [comment]
The idea I have is that display locking can help because it is a way of signalling that layout of a subtree
is paused or detached. We could take advantage of this to treat locked elements as contributing
to their containing block's layout overflow, but only in an approximate sense. The browser could
internally scale the estimated sizes from locked elements, similarly to how
https://github.com/bvaughn/react-virtualized/issues/396 works.

 When elements become unlocked, they naturally become actually laid out and contribute their exact heights to scroll height (or width, for horizontal scroll.

@fergald @rakina WDYT?

**Comment by andyearnshaw** [comment]
Interesting, how would the browser "approximate" the size? Doesn't this mean that you would need all *x* million elements present in the DOM, locked?

**Comment by chrishtr** [comment]
It does mean that the DOM would have to include X million elements.

Re how to approximate: the display locking API will include options in the acquire() method that
will specify a placeholder size for locked content.

**Comment by andyearnshaw** [comment]
> It does mean that the DOM would have to include X million elements.

Isn't that horribly inefficient? The vast majority of them will likely never be scrolled into view (I expect most of our users will filter or search). I just ran a simple test in my dev tools and it took 3 minutes and 15 seconds to append 10 million `<div>` elements to a document fragment in Chrome running on the latest MacBook Pro. I used a document fragment as I expect appending to a display locked element would optimally be about as fast.

We have, potentially, over 100 million list items, which would be elements with descendant elements. We obviously can't load all this data in one go, we can't even create all the elements in a reasonable time frame and we can't expect to hold `1e8 * elementsPerListItem` DOM elements in memory per instance of the component. Our only option appears to be virtualisation.

I totally get the benefits for display locking, with accessibility being something I've been forced to make some compromises on currently (and I'm looking into alternatives to improve accessibility), but things like find-in-page, fragment links, focus navigation and indexability are not and never will be requirements for our list or grid components.

**Comment by chrishtr** [comment]
> I totally get the benefits for display locking, with accessibility being something I've been forced to make some compromises on currently (and I'm looking into alternatives to improve accessibility), but things like find-in-page, fragment links, focus navigation and indexability are not and never will be requirements for our list or grid components.

I agree that for data sizes as large as you're describing, virtualization is required due to memory
and time constraints.

**Comment by chrishtr** [comment]
A related bug was filed/is being fixed in the current implementation. We need to make sure that scrollers with "content" larger than the maximum scrollable area are handed gracefully. @fergald 

https://chromium-review.googlesource.com/c/chromium/src/+/1825579

**Comment by vmpstr** [comment]
The proposal has changed a bit and I think this discussion was already resolved, so I'm going to close. Feel free to reopen.
