### ISSUE TITLE
Intrinsic sizing while locked

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#50]
We need to decide upon out the layout behavior of locked elements while locked, and how to supply placeholder sizes to acquire() in cases when we don't want to pay for layout of the subtree.

[This document](https://docs.google.com/document/d/10xMty7FpMLmHG5xYGEmCsxvq6LDQL0RqyfIXehvQarU/edit#) lays out possibilities, tradeoffs and use-cases.

Proposed resolution is:

*MVP*:

`displayLock.acquire({size: [a, b]})` will lock the element and lay it out as if it has contain:size CSS with width=a, height=b in place of the border-scrollbar-padding size. acquire() will resolve immediately, without waiting for a render.

`displayLock.acquire()` is equivalent to displayLock.acquire({size: [0, 0]})

*Post-MVP/lower priority*:

`displayLock.acquire({size:auto})` will delay acquisition until the next render, and set
the size to be the laid-out size of the element, as well as computing the min- and max- intrinsic sizing of the subtree

`displayLock.acquire({size: none})` will acquire immediately, and not allow the presence of the locked root to influence style or layout in any way.

**Comment by vmpstr** [comment]
> acquire() will resolve immediately

To be a bit pedantic here, acquire() is going to lock the element immediately and return a promise. Is this promise going to also resolve immediately or resolve after applying the placeholder size, doing layout, and clearing the painted output? IOW I agree that we will lock immediately, but we still will need a frame to do some work. Does the promise resolve before or after that?

> displayLock.acquire({size: none})

To confirm, based on this, for the MVP and going forward, we will _not_ have a locked-before and locked-after distinction, correct? For the MVP it will always be what we have called "lock after append". With size: none for lower priority will act as what we have been calling "lock before append" and size: auto will act as what we currently have (layout and measure and use that as size). Is this correct?

**Comment by chrishtr** [comment]
> > acquire() will resolve immediately
> 
> To be a bit pedantic here, acquire() is going to lock the element immediately and return a promise. Is this promise going to also resolve immediately or resolve after applying the placeholder size, doing layout, and clearing the painted output? IOW I agree that we will lock immediately, but we still will need a frame to do some work. Does the promise resolve before or after that?

Hmm. I guess resolving after layout and clearing the paint does make more sense, let's do that.

> 
> > displayLock.acquire({size: none})
> 
> To confirm, based on this, for the MVP and going forward, we will _not_ have a locked-before and locked-after distinction, correct? For the MVP it will always be what we have called "lock after append". With size: none for lower priority will act as what we have been calling "lock before append" and size: auto will act as what we currently have (layout and measure and use that as size). Is this correct?

Correct. The parameter to acquire() now completely determines the semantics, not whether it was locked while disconnected from the DOM.

**Comment by vmpstr** [comment]
> as if it has contain:size CSS with width=a, height=b in place of the border-scrollbar-padding size

Also to clarify here, this can still be overridden by CSS style, right? Ie, if we have acquire(size: [100, 100]) but the element has width: 50wv; then we would size the box to be 50% of the viewport and 100 in height.

**Comment by chrishtr** [comment]
> Also to clarify here, this can still be overridden by CSS style, right? Ie, if we have acquire(size: [100, 100]) but the element has width: 50wv; then we would size the box to be 50% of the viewport and 100 in height.

That wasn't the intention. Do you think it's better to be overridable by CSS style?

**Comment by vmpstr** [comment]
I can see the benefit if it can still be sized by style. Just in terms of contain size behavior, the box is conceptually empty but still subject to style constraints. Here, the box would be of a given size, but still subject to style constraints.

This is also particularly important to answer for things like flex where we would have to decide whether this is the constrained size or unconstrained size (ie can flex change the size of the box at all)

**Comment by chrishtr** [comment]
Ok let's go with your suggestion then (*can* be styled).

**Comment by vmpstr** [comment]
That sounds good

**Comment by vmpstr** [comment]
Another question here is what to do in cases where we have a locked element with actual size containment.

Specifically, should we respect size containment and lay it out as empty, or should display locking win here and have a locked content size instead?

**Comment by chrishtr** [comment]
> Specifically, should we respect size containment and lay it out as empty, or should display locking win here and have a locked content size instead?

I think the size containment should win.

**Comment by vmpstr** [comment]
deprecated in favor of content-size
