### ISSUE TITLE
Blanking vs locking

### ISSUE THREAD

**Issue by jakearchibald** [WICG/display-locking#52]
At blinkon, it sounded like the idea was to lock the layout, and blank the pixels. Did I understand that correctly?

I'm interested in using display-locking for an element that's transitioning, eg blurring and fading.

During this transition, something like a hover effect will cause the layer to repaint, and likely jank the animation.

I was hoping I'd be able to use display-locking to prevent this, but if it's going to blank out the pixels, it doesn't work for me.

cc @surma

**Comment by chrishtr** [comment]
Blurring and fading should be fast to apply effects. Can you give a specific example that is slow?

**Comment by surma** [comment]
I don’t think blurring can be considered as fast, unless something has changed in the last year in how we blur. It is slow enough to warrant [dedicated technique to animate a blur](https://developers.google.com/web/updates/2017/10/animated-blur). 

I think the problem Jake was describing is if an element on the blurred element reacts to hover, the blur would have to be re-calculated and re-painted, which could make the entire animation jank.

**Comment by chrishtr** [comment]
@surma Right, ok. I had forgotten about the blur article you wrote.

However, the blur will not cause any layout by itself, even without the optimizations you described, unless there is some other invalidation of layout or style happening (and this is the case Jake mentioned).

I do agree that there are use cases for keeping around the pixels while rendering is locked. I hope we can add this feature at some point in the future.

**Comment by jakearchibald** [comment]
Blurring is often the slowest of the paints for me. That's why I used it to demonstrate the issue in https://bugs.chromium.org/p/chromium/issues/detail?id=941923

**Comment by jakearchibald** [comment]
But, I'm not specifically talking about blurring here, I'm talking about any layer that cannot paint at 60fps.

**Comment by vmpstr** [comment]
I think this example is a reason for something like render=async, which would separate the performance of the render=async element from the rest of the page.

Display locking (or rendersubtree) can likely be used to implement render=async (on the browser side), but I think display locking on its own would continue to blank pixels. The main reason for this is that display locking provides the developer full control for how long to keep the content locked, meaning we could be displaying stale pixels indefinitely. This in turn is hard to explain, and may be a problem if the user tries to interact with the stale pixels.

render=async should solve this by not letting the developer control how long to lock things, simply to update things without causing jank (even if the updates take more than 1 frame).
