### ISSUE TITLE
Spec innerText interactions with s-v

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#54]
I think we should not yield any innerText results when querying a locked subtree (similar to visibility: hidden).

**Comment by chrishtr** [comment]
Why should innerText not yield anything? The subtree conceptually has layout.

**Comment by rakina** [comment]
Yeah I think this should be returning the normal values - essentially forcing layout when innerText is calculated.

**Comment by fergald** [comment]
innerText is only supposed to include visible text. People expect locked content to be invisible so, e.g.

```html
<div id=outer>
  we should
  <div rendersubtree=invisible>
    not
  </div>
  invade mars.
</div>
```

it seems like `outer.innerText === 'we should invade mars'` and we locked `outer` then the whole thing would be `''`.

However I think it's arguable that if it was also activatable, then querying `innerText` would activate it and get the full text. I kind of feel like `innerText` is short-hand for selecting an element and getting it's stringified value.

```js
const el = document.getElementBySomething(...);
const sel = window.getSelection()
sel.addRange(/* el */);
sel.toString();
```

Is there a use case for an innerText for alternate definitions?

**Comment by fergald** [comment]
I would say that activatable signals that the element is still semantically part of the document's content but invisible for performance reasonse, not having activatable means the element is semantically not part of the document's content.

I'm not sure what you mean by "available to imperative rendering APIs such as getBoundingClientRect". A call to `getBoundingClientRect` on a containing element will currently behave as if this text is not there, so it seems correct that `.innerText` on that element would also not contain the text.

I think I have 2 fairly good examples for why it should exclude invisible non-activatable text.

Example: I am introducing a new element to replace an old element and I'm using locking to make it atomic without jank. Should `innerText` return the text of both the unlocked element and its pending replacement? That seems wrong.

Example:

```html
<div id=outer rendersubtree="invisible">
  0
  <div>
    1
    2
    ...
    10,000,000
  </div>
  10,000,001
</div>
<script>
  outer.getBoundClientRect(); // space for 2 lines of text
  outer.innerText; // 2 lines of text or 10,000,002 lines of text?
</script>
```

What's the use case or reasoning for choosing 10,000,002 lines of text?

**Comment by vmpstr** [comment]
I can see an argument for why we'd want to get all of the text for `auto` since it essentially could be the same as selection which is supposed to select everything. For things that are invisible though, (ie hidden) we should not be returning any innerText.

**Comment by chrishtr** [comment]
Just tried a test:

```
<!doctype HTML>
<div id=target style="visibility:hidden">
    abcdefg
</div>
<script>
    console.log(target.innerText); // Prints the empty string
</script>
```

Therefore innerText under skipped subtrees should also return the empty string.
