### ISSUE TITLE
Locking replaced content

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#58]
Replaced elements, i.e  `<img>`, `<video>`, `<embed>`, `<object>` and `<iframe>`, paint their
replaced content atomically in the "foreground" phase of painting. If a replaced element is
locked, then I think this foreground content should not be painted, and rendering work should
be skipped.

If update() is called on a lock of a replaced element, then the work can be done asynchronously (e.g schedule image / video decodes on background threads). Blink already does image and video decoding in other threads/processes, regardless, but while locked but not updating this work can be avoided.

SVG images are drawn in their own document, and this work can be done cooperatively / on a background thread as well.

**Comment by chrishtr** [comment]
For iframes, there is the question of whether rAF callbacks should run if the iframe is locked.

It seems that it should *not*, but when update() or updateAndCommit() or commit() is called, they should be called exactly once, since conceptually there is a rendering update on the iframe.

**Comment by vmpstr** [comment]
I'm a little weary about pausing script at this point. I think rendersubtree, as is the direction we're moving into, should only pause rendering. rAF can be considered part of rendering, but to me the difference between constructing the DOM and rendering is pretty separate. WDYT? 

My vote is to keep script running

**Comment by chrishtr** [comment]
Rendering and rAF have to happen together or not-happen together. That's the way the web rendering model works..

**Comment by vmpstr** [comment]
What I mean to say is that rAF should be used to construct the DOM part of rendering. My understanding of rendersubtree is to control the style layout and onward part of rendering. 

For example in rAF, I'm unsure how to draw the distinction between whether an update applies to "self" or "subtree", which from the UA perspective it's just script. Whereas style, layout, etc have a clear concepts of whether something applies to the element with the rendersubtree attribute or to a descendant of such an element.

**Comment by vmpstr** [comment]
I think I'm getting my wired crossed with #60 which is basically the same point, but from within the document

**Comment by chrishtr** [comment]
> What I mean to say is that rAF should be used to construct the DOM part of rendering. My understanding of rendersubtree is to control the style layout and onward part of rendering.

Yes. Or more generally all parts of the rendering lifecycle controlled by the browser (including custom elements and resource loads).
 
> I'm guessing that's the whole point is that if we lock the documentElement, then everything is in the subtree hence we can skip raf?


Yes. Or if an ancestor owning element of the document in some other frame is also locked, that counts as well.

**Comment by vmpstr** [comment]
This shoulds good, let's merge into #60
