### ISSUE TITLE
We should prevent rAF and lifecycle updates altogether if documentElement or parent are locked.

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#60]
Consider the case of locking the root element of the root frame, or the root element of a frame embedded in a cross-origin parent frame:

document.documentElement.displayLock.acquire();

This should of course blank out the frame's paint and avoid rendering cost, but we can do more: we can avoid running a BeginMainFrame entirely. This avoids costs like:
(a) rAF callbacks
(b) input event processing
(c) compositor commit

because none of them can actually do anything useful if the whole document is locked.

In addition to the above benefits, they also provide a developer API to opt into the DeferBeginMainFrame behavior / DeferCommit Chrome already heuristically supports during page load. Thus an app that wants to e.g. avoid extra rendering which may slow down page load may do so.

**Comment by vmpstr** [comment]
I think that's a reasonable follow up. I'm a bit unclear about particular usecases of doing this from within the frame vs from outside of the frame. In particular, if things like rAF callbacks aren't running and input isn't being processed, what would let the document element be unlocked? Just timeouts / post messages?

**Comment by chrishtr** [comment]
Yes, just timeouts / postMessage.

**Comment by vmpstr** [comment]
See #58 for more discussion

**Comment by chrishtr** [comment]
Another point that complicates the picture: activation of content within cross-origin iframes may leak privacy.

Therefore if we have a setup like:

```
<div rendersubtree="invisible activatable">
  <iframe src="cross-origin.com"></iframe>
</div>
```

Then it seems we can't activate such content.

**Comment by chrishtr** [comment]
https://github.com/whatwg/html/issues/4861
