### ISSUE TITLE
rendersubtree & content-size proposals + discussion

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#62]
Some of the display locking API can be expressed via new CSS properties. For example, we could have:

`subtree-rendering: invisible` meaning the element has a not-rendered subtree that has contain: size style layout
`subtree-rendering: activatable` meaning `rendering: invisible` plus activatable by the browser
`content-width`, `content-height` meaning the size of subtree content to use as an input to layout of a `contain: size` element

Then `el.displayLock.acquire({size: [100, 200], activatable: true})` would be equivalent to:

```
el.style.subtreeRendering = ‘activatable’;
el.style.contentWidth = 100;
el.style.contentHeight = 200;
```

These properties together would allow the browser to unconditionally skip rendering the subtree, just like display locking.

`el.displayLock.commit()` would be equivalent to:
```
el.style.subtreeRendering = ‘auto’;
el.style.contentWidth = ‘auto’;
el.style.contentHeight = ‘auto’;
```

There is no CSS equivalent to `update()` or `updateAndCommit()` though, or the `beforeactivate` event. Those methods / events would still be added to the element’s API surface.

The advantages of moving the concepts of `acquire()` and `commit()` into CSS include:
1. Avoids an issue in the current spec that it’s not great to introduce API methods which have layout side-effects without going through CSS (the contain:size + content-size side-effect of `acquire()`).
2. Supports use of the acquire/commit parts of the API without script

Regardless of whether this is good change, we could still use these CSS properties to define what the `acquire()` and `commit()` methods do, they could also be defined in terms of their effect on computed style and layout via those CSS properties. And they may be of independent interest.

**Comment by fergald** [comment]
What happens when an element activates? If it's invisible due to a rule in a style-sheet, that rule will remain in place? Is activated a state that is temporary turns back on render but goes away once e.g. the FIP is no longer finding this element? Then the element would go back to be invisible? I don't see anything wrong with per-se but it's different.

**Comment by chrishtr** [comment]
Good questions. This idea came up today so it may/probably has flaws that we didn’t know about, maybe you found some.

> What happens when an element activates? If it's invisible due to a rule in a style-sheet, that rule will remain in place?

I’m not sure what example you’re thinking of with invisibility, can you give one?

 Is activated a state that is temporary turns back on render but goes away once e.g. the FIP is no longer finding this element? Then the element would go back to be invisible? I don't see anything wrong with per-se but it's different.

I was assuming it would be the same as activation with the current imperative API. Script would still need to listen for beforeactivate and “re-lock” (by adding the CSS back).

Hmm. Maybe it is weird that the UA removes certain style when activating (but not other styles… ). That may be a reason to keep acquire() and commit().

**Comment by fergald** [comment]
By invisible I mean locked. So e.g.

```html
<style>
  div { contain: style layout; subtreeRendering: activatable}
</style>
<div>
  find me!
</div
```

So the UA can't really "remove" the style, it's in the sheet, it wasn't programmatically assigned.

We can say that it makes it locked when it's not the current result and it goes back to being locked when it stops being the current result but I don't think we can say it unlocks it and leaves it unlocked because that contradicts the style-sheet.

**Comment by chrishtr** [comment]
That’s a really good point. This is a strong argument for making it a programmatic API, since the user agent is programmatic, and it’s problematic for the user-agent to try to tweak style sheets for the reasons you mentioned.

@flackr @vmpstr WDYT of this point?

**Comment by vmpstr** [comment]
I was thinking about this yesterday and it seems that the proposal is essentially the original searchable-invisible-dom + imperative update(). Do you recall how this was addressed in the original searchable-invisible proposal?

**Comment by vmpstr** [comment]
I guess the difference is that searchable-invisible as far as i remember wasn't CSS but element properties, which the UA can remove?

**Comment by flackr** [comment]
Perhaps I'm missing something, but I would have expected the element to only be unlocked so long as it was the current result, and that it would implicitly go back to being locked after it stops being the current result as @fergald suggested.

Just as its up to the developer to unlock the adjacent items if they should be visible it's also up to the developer to unlock (remove the style on) the activated item if it should remain visible, right?

**Comment by vmpstr** [comment]
In the display locking as we have it now, the lock is not reacquired. I think there are a few activation scenarios like find-in-page or tab navigation or anchor link navigation where it becomes unclear when the action is "done" and we can relock. 

It's conceivable that we issue a beforeactivate signal and if it's not handled by unlocking the element then it relocks?

**Comment by chrishtr** [comment]
Also, for virtual-scroller it’s undesirable to re-lock, because that causes the element subtree not to paint and change its layout. As long as script code manages off-screen-ness, then the UA should leave it unlocked, because unlocked is the correct visible layout for the user.

**Comment by chrishtr** [comment]
Also, the parts about content-width/content-height still seem useful as a CSS feature to explain and maybe useful in non-DL use cases.

**Comment by chrishtr** [comment]
Yet another option is that the user agent could fire activation events when it wants to display content that is under `subtree-rendering: activatable`, but not actually change the CSS afterward. Content
would be expected to mutate CSS in the event handler in order to show the content.

This would get around the problem of the user agent weirdly modifying CSS and contradicting style sheets, but introduces the problem of buggy content interfering with find-in-page, by failing to display it properly.

**Comment by chrishtr** [comment]
Yet another option is to use attributes on HTML elements to represent rendering states. e.g.

`render=async|auto|sync|locked|activatable`

`render=locked` is like calling `displayLock.acquire()`
`render=activatable` is like calling `displayLock.acqure({activatable: true})`

`render=async|auto|sync` indicates the default UA restrictions on whether the subtree presents atomically w.r.t. the outer content.

**Comment by chrishtr** [comment]
I think the most feasible alternatives for basic locking appear to be:

a. The current, imperative API
b. HTML attributes

(the update() method I think needs to be imperative)

Advantages of (a):
* Better hiding of the details of what is is or is not rendered (if a web component used locking for its shadow DOM, code outside of the web component would not observe any attributes changing on slotted light DOM)
* Provides natural opportunities for content to observe state changes (by listening to resolution or rejection to `acquire()`, `commit()`, etc)
* Aligns a bit better with presence of `update()`

Advantages of (b):
* Compatible with progressive enhancement bootstrapping techniques that don’t use script
* Can be explained more easily terms of the existing cascade of element -> attributes -> CSS for defining style and layout

I think the APIs are functionally equivalent otherwise. In particular, the Display Locking implementation we have in Chromium right now can be adapted to work with either approach easily.

**Comment by chrishtr** [comment]
Another use-case enabled nicely by the attribute approach is styling in response to lock state:

.lockedDiv[render=locked] {
  background-image: url(spinner.png);
}

**Comment by chrishtr** [comment]
Also, @tabatkins pointed out there is not necessarily any need to choose imperative or atttributes - we could do both. If you set the attribute on the element, it would lock/unlock as appropriate. If you call acquire() or commit(), it would do the same, but also reflect in the attribute changing automatically. Same for the user agent activating the lock.

**Comment by rakina** [comment]
One advantage of the imperative API was the sizing, I think - each locked element can be sized differently  (like in virtual scroller, where newly locked elements will use current average height)  quite easily by just adding the "size" option. While with the declarative API, I assume we will use size from CSS - so styling each element in a scroller with a different size will be harder (if we don't want to sprout the style attribute)?

But I guess using the style from CSS is way easier to understand and more consistent, and we don't need to relayout due to size changes (in most cases?) when we commit.

**Comment by tabatkins** [comment]
We're thinking there's still a missing primitive in CSS to allow for the sizing: some way of saying "be contain:size, but rather than acting like you have *no* children, act like you have *one* child of this specified size".

**Comment by chrishtr** [comment]
Here's as minimal a proposal as I can come up with, involving just declarative attributes and CSS (w/help of @rakina and @vmpstr):

1. Add a `render=auto|invisible|activatable-invisible` attribute. A non-`auto` value of this attribute means "don't paint or hit test this content". If the value is `activatable-invisible`, then the user agent can remove the attribute if it wants, when performing an activation. If the user agent removes the attribute due to activation, it *must* remove the attribute *before* the next rendering update, with an intervening microtask checkpoint available to script.

3. A `content-size` CSS property that says to layout as if it had one child of the given size, if the element also has `contain:size`.

4. an `updateRendering()` method on Element that tells the browser to "prepare to render" in the background, and resolve the returned promise when it's ready to render "without undue delay".

That's it. There is no restriction on which elements can have any value for 'render'. There is no 'beforeactivate' event. (Maybe we should just add this event as a convenience though.)

In terms of implementation, if an element happens to have `contain:style layout size`, and has `content-size` set, and has `render=invisible` or `render=activatable-invisible`, then all lifecycle phases can be skipped for the subtree during a rendering update. Otherwise they can't, except for paint.

In the future, additional variants of `content-size`, such as `aspect-ratio`, could be added.

Based on this, the Display Locking API would be polyfilled as follows:

```
/* Developer promises to not call this API for elements which don't have contain: style layout, or performance will suck. */

<style>
[render="activatable-invisible"],
[render="invisible"] {
  contain: size;
  contents-size: <width>, <height>
}
</style>
element.displayLock = {};
element.displayLock.acquire = (options) => {
  if (options['activatable'])
    element.setAttribute('render', 'invisible-activatable');
  else
    element.setAttribute('render', ' invisible');
  // The "size" option should be put in CSS instead; see <style> tag above.

  let promise = new Promise();
  window.requestPostAnimationFrame(() => promise.resolve());
  return promise;
}

element.displayLock.commit = () => {
  element.setAttribute('render', 'auto');

  let promise = new Promise();
  window.requestPostAnimationFrame(() => promise.resolve());
  return promise;
}

element.displayLock.update = () => {
  updateRendering();
}

// Replaces 'beforeactivate' event.
let callback = (mutationList) => {
  mutationList.forEach(function(mutation) {
    if (mutation.target.getAttribute('render') != 'invisible' && mutation.target.getAttribute('render') != 'activatable-invisible')
    var event = new Event('beforeactivate');
    mutation.target.dispatchEvent(event);
  });
}
 let observer = new MutationObserver(callback);

let addBeforeActivateCallback = (element) => {
  observer.observe(element,  attributeFilter: ['render']);
}
```

**Comment by vmpstr** [comment]
Activatability aside, would it be fair to say that invisible vs auto can be accomplished with

```html
.invisible {
  visibility: hidden;
  contain: size;
  content-size: width height;
}
.visible {}
```
The only property of being render=invisible that I think visibility hidden doesn't have, is that the subtree can't be visible (whereas it can with visibility: visible on a descendant).

The "contain: size" portion is a little suspect to me as well, since that would override any other contain properties the element may have (it doesn't just "add" contain: size, right? it replaces whatever containment there is with contain: size)

I also suspect that beforeactivate would be a commonly used signal if render attribute is used, so although the polyfill seems fine, I think we still want the convenience of a separate signal.

Overall I'm supportive of trying this out, but I'm concerned that there are some performance cliffs here. Specifically, we don't paint in all cases, but depending on which containment properties it has, we may be fast, or may not be fast. Not that the display locking provided these guarantees, but at least it had a notion of rejecting an attempt to lock due to containment not being satisfied. And, again, I keep thinking of what could be another proposal here that simply captures "activatability" and otherwise just cleverly optimizes visibility: hidden under similar containment constraints.

**Comment by chrishtr** [comment]
> Activatability aside, would it be fair to say that invisible vs auto can be accomplished with
> 
> ```
> .invisible {
>   visibility: hidden;
>   contain: size;
>   content-size: width height;
> }
> .visible {}
> ```

There are two differences. One, visibility: hidden can be overridden by descendants, and two, the root element is still rendered, just not the subtree. (I didn't say that in my previous comment, but that's the model we've been using so far, in order to support the fallback-content use case.)

> The "contain: size" portion is a little suspect to me as well, since that would override any other contain properties the element may have (it doesn't just "add" contain: size, right? it replaces whatever containment there is with contain: size)

Hmm. Yes that's a problem. Either we'd have to allow a way to have containment be additive, or change the style sheet to:

```
<style>
[render="activatable-invisible"],
[render="invisible"] {
  contain: style layout size;
  contents-size: <width>, <height>
}
</style>
 ```

In fact, on further reflection last night, I was thinking of specifying that the above rules (except for the `contents-size` part) should be a user-agent stylesheet rule. This would be overridable by the developer if really desired, but would reduce accidental footguns.

> I also suspect that beforeactivate would be a commonly used signal if render attribute is used, so although the polyfill seems fine, I think we still want the convenience of a separate signal.

I agree. The reason I put in the polyfill is that I wanted to see what is the absolute minimum number of new features.
 
> Overall I'm supportive of trying this out, but I'm concerned that there are some performance cliffs here. Specifically, we don't paint in all cases, but depending on which containment properties it has, we may be fast, or may not be fast. Not that the display locking provided these guarantees, but at least it had a notion of rejecting an attempt to lock due to containment not being satisfied. 

Only if you catch the promise rejection though, right? It's been common in testing with early dogfooders that they misunderstand at first or forget to add the right containment CSS, so I'm not sure the current API achieves the goal of preventing bad performance.

>And, again, I keep thinking of what could be another proposal here that simply captures "activatability" and otherwise just cleverly optimizes visibility: hidden under similar containment constraints.

Hmm, Isn't that what this latest proposal does though?

I think the main difference between the latest proposal I posted last night and previous attempts is giving up on the notion of forcing a dependency of the `render=invisible` concept and `contain: style layout`.

**Comment by vmpstr** [comment]
> Only if you catch the promise rejection though, right? It's been common in testing with early dogfooders that they misunderstand at first or forget to add the right containment CSS, so I'm not sure the current API achieves the goal of preventing bad performance.

Yes, you're absolutely right. The difference is that if the display lock is rejected, we paint the contents. So it should be clear to anyone testing this that something didn't quite work. With the proposal here, we won't paint, so it looks like everything is working (and it is working, just not optimally). 

> > And, again, I keep thinking of what could be another proposal here that simply captures "activatability" and otherwise just cleverly optimizes visibility: hidden under similar containment constraints.
> 
> Hmm, Isn't that what this latest proposal does though?

I suppose. What I meant to say is that this is adding yet-another-way to make content not be visible to CSS/HTML, but now with activatability! What I'm wondering is if there is a way to cleanly piggy back on existing notions. As a (not so well thought out) example, suppose we have `beforeactivate` on all elements, not just `render=invisible-activatable` ones, then we can "polyfill" `render=invisible|invisible-activatable` with say `opacity: 0` to prevent subtrees from overriding the value, or `visibility: hidden-forced` to indicate that descendants can't override this value, then we can already optimize everything display locking hopes to optimize, and script can react to activations due to the signal. These are CSS things, so it's a bit different from attributes, but at first blush, I don't see a strong need for a new attribute.

**Comment by chrishtr** [comment]
> Yes, you're absolutely right. The difference is that if the display lock is rejected, we paint the contents. So it should be clear to anyone testing this that something didn't quite work. With the proposal here, we won't paint, so it looks like everything is working (and it is working, just not optimally).

Consider a site that tries to lock things off-screen, and fails to do so because the CSS isn't set up right. Painting won't necessarily help them debug, because it it was offscreen anyway.

I think the user-agent stylesheet rule I mentioned in my previous comment, plus a devtools warning, may be enough.
 

> I suppose. What I meant to say is that this is adding yet-another-way to make content not be visible to CSS/HTML, but now with activatability! What I'm wondering is if there is a way to cleanly piggy back on existing notions. As a (not so well thought out) example, suppose we have `beforeactivate` on all elements, not just `render=invisible-activatable` ones, then we can "polyfill" `render=invisible|invisible-activatable` with say `opacity: 0` to prevent subtrees from overriding the value, or `visibility: hidden-forced` to indicate that descendants can't override this value, then we can already optimize everything display locking hopes to optimize, and script can react to activations due to the signal. These are CSS things, so it's a bit different from attributes, but at first blush, I don't see a strong need for a new attribute.

I think the key is that the optimizations have to be:
* done with an attribute or some non-CSS mechanism, because activatability won't work otherwise
* with the whole thing being simple enough to use that developers aren't likely to use it wrong.

So there has to be an attribute that the user agent can remove, which unless the developer is doing really wrong things, will allow the content to be visible to find-in-page and other features, but not otherwise. A simple webpage that just has those attributes and nothing else should Just Work.


<div id=myExpensiveContent render=invisible-activatable></div>

This does not require that the attribute itself force not-painting. One could imagine a modification to the user agent stylesheet rule I proposed like this:

```
<style>
[render="activatable-invisible"],
[render="invisible"] {
  contain: style layout size;
  visibility: hidden-forced; /* or visibility: subtree-hidden-forced */
}
</style>
```

which separates out the invisibility concept from the attribute, and allows the developer to override it if they really want.

I don't think visibility:hidden is enough, since that is overridable. I don't think opacity:0 is enough by itself because it just turns off paint (and loses the painting of the root element, but maybe we can skip that in a minimal solution). pointer-events: none is not enough because that can be overridden by children.

**Comment by flackr** [comment]
Is there a reason that activation couldn't be synonymous with being currently in visible range of ancestor scroll ports - which would be well defined when an activation could end? E.g. strawman proposal:

```html
<style>
.list-item {
  contain: style layout paint offscreen-size;
}
</style>
<div class="list-item" content-height="200">...</div>
```

While offscreen, the element assumes its `contentHeight` and when onscreen changes size. When combined with scroll anchoring this should produce no content shift in either scroll direction. This is effectively the [`height-auto` proposal](https://github.com/w3c/csswg-drafts/issues/1043) without automatic sizing.

Then, if you combine this with an event for when the element becomes visible you could may be able to update the content size using the current (uncontained) layout dependent size.

**Comment by chrishtr** [comment]
> Is there a reason that activation couldn't be synonymous with being currently in visible range of ancestor scroll ports - which would be well defined when an activation could end? E.g. strawman proposal:

The reason it's not there now is to simplify the job of the browser and not bake this behavior into the platform.

> One notable missing piece is the developer doesn't have a direct way to hint to the browser that it should prepare to show the element if the browser can't already figure it out (i.e. due to being near to the current scroll position).

 Is that what `updateRendering()` would do?

**Comment by tabatkins** [comment]
So, MVP:

1. `rendersubtree="<nothing> | visible | invisible | invisible-activateable"`
    `""` and `"visible"` do the same thing
    
    `"visible"` imposes the minimum necessary containments to not have layout flicker when activated. (layout, style). `"invisible"` and `"invisible-activateable"` do the specified things. We expect the author to start an element out with `rendersubtree` as a boolean, to get it ready for being invisible'd (and probably have a devtools error 

2. Add 'content-size' property to CSS. Only has effect if size containment is applied; makes the element, rather than laying out as if empty, lay out as if it has a single child of the specified size.

3. Add the convenience functions `.acquire()` and `.commit()`, which just adjust the attribute for you and return a promise resolving at the next animation frame (which is when the effects of the added/removed attribute will be visible).

4. Add the `.updateRendering()` method, which provides a prioritization hint to the UA that you'll want to display the contents soon, and which returns a promise for when the UA is "ready".

**Comment by chrishtr** [comment]
> So, MVP:

Looks about right. One comment below.

> 3\. Add the convenience functions `.acquire()` and `.commit()`, which just adjust the attribute for you and return a promise resolving at the next animation frame (which is when the effects of the added/removed attribute will be visible).

I don't think we need these, if we have requestPostAnimationFrame().

**Comment by chrishtr** [comment]
(future-looking comment)

We could also add `rendersubtree=static` to indicate that the DOM should not execute custom element upgrades. Thus it can have maximum page-load performance. This feature was prototyped against the older searchable-invisible DOM API by @rakina last year, and seems like it should be feasible.

**Comment by chrishtr** [comment]
Tenatative spec language for the rendersubtree attribute is [here](https://github.com/whatwg/html/compare/master...chrishtr:rendersubtree-attribute).

**Comment by tabatkins** [comment]
And here's the tentative proposal for [the 'content-size' property](http://tabatkins.github.io/specs/css-content-size/).

**Comment by vmpstr** [comment]
This is more or less resolved, but let's keep this open for the useful links

**Comment by chrishtr** [comment]
https://github.com/whatwg/html/issues/4861
