### ISSUE TITLE
Activatable: reacquiring/committing in beforeactivate.

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#63]
What should happen if we have a beforeactivate handler, which when triggered re-acquires the lock (with maybe not activatable?) or just commits the lock before the code has a chance to unlock it?

The latter should be straightforward: we just accept the fact that we're committing and proceed.
The former however, I'm unsure: should a re-acquire stop the activation? Can we reacquire with still being activatable to prevent _this_ activation?

/cc: @chrishtr @rakina

**Comment by vmpstr** [comment]
We would also need to consider all sources of activation here, like scrollIntoView and all

**Comment by vmpstr** [comment]
Also if we have a nested chain of things, and we issue beforeactivate starting from the bottom, and the top most element reacquires with no activation, it's unclear what that means... Technically we sent beforeactivate signals everywhere but will not activate, since toplevel thing is locked.

Presumably the beforeactivate signal can also acquire a lock on its own ancestor, which would also cause some weirdness, but that's up to script to do. So maybe this is all OK.

**Comment by chrishtr** [comment]
`scrollIntoView` doesn't activate, as we decided that scroll should not activate.

If a root locked element re-locks with` activatable: false` during the `beforeactivate` event then it should be invisible to the user-agent feature in question. After return from `beforeactivate` the user agent will have to check if it's still in an activatable or unlocked state.

Also, `beforeactivate` happens before the user agent unlocks, so there seems no conflict of states regarding 're-lock in `beforeactivate`?

**Comment by vmpstr** [comment]
Yeah my question was more that beforeactivate event wouldn't have a preventDefault() type of action. Ie, i received a before activate, but i'd like to not activate and keep me locked. There's currently no way to accomplish that. 

If we consider that "activation" is distinct from "being unlocked", then one could argue that we can first unlock, then issue a beforeactivate signal, which is meant to say "if you do nothing, we will display the contents". However, this might give the script opportunity to say "i'd like to keep this hidden" and reacquire the lock. Does that make sense? I'm not suggesting we should go this way, but I think it's a little bit awkward that there is no way to abort anything in beforeactivate.

**Comment by chrishtr** [comment]
...and Vlad pointed out to me that `scrollIntoView` does in fact activate. It's regular scrolling gestures that do not.

**Comment by rakina** [comment]
Having a way to prevent unlocking sounds reasonable. It also means authors can't use the beforeactivate event as a signal that an element gets displayed 100% of the time though (there might be something that stays locked up the tree), which I guess is ok. I vaguely remember discussing something similar to this with @fergald, maybe he has more to say on this.

**Comment by vmpstr** [comment]
Presumably authors can't use this guarantee even with current implementation, since some other handler may either lock an ancestor of the activated element, or do something like
```javascript
requestAnimationFrame(() =>  e.target.displayLock.acquire());
```

To be clear, I'm not arguing one way or another, since I don't have a use-case where I would want a lock to be reacquired in beforeactivate. However, I weakly prefer there to be a way since it makes the API a bit more flexible.
