### ISSUE TITLE
Tabbed navigation usecase discussion.

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#64]
There's a usecase for display locking, which is tabbed navigation. 

There are some problems with it:
- Hit-testing: it seems that if there is a div on top of some text content, then we can't select it. As an example:

```html
<!doctype HTML>
<style>
.cover {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
</style>

<div>This is some text</div>
<div class="cover"></div>
```

"This is some text" is not selectable, and the cursor doesn't change to text selection when hovered over the text, since there is a transparent div covering it. We essentially run into the same situation with trying to hide a tab. We'd need to size it to 0x0 or something similar instead.

- Activation: we have considered a multitude of events that cause activation. The prominent example is find-in-page, which for this case should work as intended. However, things like tab navigation or selection should probably not activate content that is display locked.

I'm not sure what the solution is here. There are different use-cases which require or desire different activation events. Should there be a set of activatable events that can be specified? Ie activatable: [
  "find-in-page",
  "selection"
] or something like that?

We need to talk about that.

**Comment by chrishtr** [comment]
I don't really know what the selection algorithm is exactly. There is the user-agent feature, and there is the selection APIs exposed to script. The latter are spec'ed, not really sure about the user-agent feature.

Definitely the developer in this case will need a way to say "don't select things that are in the other tab" via some means. Not sure if there is a way in CSS right now to say that selection shouldn't extend across certain DOM boundaries.

**Comment by rakina** [comment]
I'm not sure I understand the problem here - does covering a display locked text with a div doesn't behave like a normal text covered with a div? Or do we want to have a display locked text that doesn't work with selections without covering it with a div?

If it's the latter - having the ability to list out things that may trigger activation sounds nice. There's also a user-select CSS property though? https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by vmpstr** [comment]
I think there are two problems:
1. The fact that we have a display locked element that is on top of another one that should be selectable. This is more of a problem in my testcase, but I think it makes sense
2. Selecting text activates elements. In my usecase, I'd like to support find-in-page activation, but not selection activation. Currently there's no way to do this.

**Comment by vmpstr** [comment]
I think the issues here were resolved
