### ISSUE TITLE
Mutation observer vs beforeactivate event

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#67]
In the declarative version, mutation observer should be sufficient. So, do we still want beforeactivate?

**Comment by chrishtr** [comment]
Not sure. I think we should implement demos against the new API and evaluate performance & ergonomics.

@fergald

**Comment by fergald** [comment]
To use MO for this you would either have to specifically observe each element that you are interested in or observe an ancestor with the `subtree` option and filter out all irrelevant node. In both cases you would also have to filter out changes to other attributes _and_ changes that change the attribute but don't signify an activation. That last one made me realize that you also couldn't distinguish an activation from a programmatic unlocking (maybe that's OK, maybe if you unlocked it you would remove the observer anyway).

Anyway, ergonomics-wise, using MO seems like a loss.

**Comment by smaug----** [comment]
The current setup where microtask checkpoint is run at somewhat random times breaks microtask model. We don't want some random pending Promise callbacks to get called when one activates a subtree.
And in general it is rather ugly model that UA changes some DOM attribute value. It really should be some kind of state change and then event telling that state will change or changed (not sure which one)

**Comment by chrishtr** [comment]
> The current setup where microtask checkpoint is run at somewhat random times breaks microtask model. We don't want some random pending Promise callbacks to get called when one activates a subtree.

Currently, microtask checkpoints happen at the end of every javascript task, and in various other places. Therefore a pending promise resolution that may be unrelated to activation of `rendersubtree` contents, must have resolved via a non-javascript task.

The `rendersubtree` PR for HTML spec adds one during each of the specified UA algorithms, after mutation fo the `rendersubtree` attribute by the UA but before it renders the final response to the UI.

Could you explain in more detail why it's "somewhat random"?

> And in general it is rather ugly model that UA changes some DOM attribute value. It really should be some kind of state change and then event telling that state will change or changed (not sure which one)

Where would that state change live? How should it connect to the cascade?

These questions are why we settled so far on the attribute.

**Comment by smaug----** [comment]
The draft says 
"When the user agent activates an element, and the element is rendersubtree-invisible, it must run the following steps before the next time the update the rendering steps run, any user input is processed that may target the element, or any algorithm may consume data about that element:

    For each ancestor of the element, in reverse order of its depth in the DOM, which has the rendersubtree attribute whose value contains activatable, set the attribute to visible.
    Perform a microtask checkpoint. "

and activation may happen for example with
"If an element is activatable, then an extra step to first activate the element should be run at the beginning of the steps to scroll the element into view."
so, element.scrollIntoView() might trigger microtask checkpoint.

Microtask checkpoints must not be run in middle of some script execution.

**Comment by chrishtr** [comment]
> Microtask checkpoints must not be run in middle of some script execution.

I agree with this statement. However, in the example of `scrollIntoView()`, the scroll is actually asynchronous to the javascript, and need not finish before running other tasks. Therefore the algorithm need not be considered to be running synchronously during the script call into `scrollIntoView()`. This can be clarified in the spec.

**Comment by smaug----** [comment]
scrollIntoView() isn't async.
https://drafts.csswg.org/cssom-view/#ref-for-scroll-an-element-into-view calls synchronously 
https://drafts.csswg.org/cssom-view/#scroll-an-element-into-view and the draft for rendersubtree then adds "an extra step to first activate the element should be run at the beginning of the steps to scroll the element into view"
I don't see where the asynchronous part comes from.
(Smooth scrolling can be async. )

And the issue applies to other cases too, like window.find();

What is the reason to use DOM attribute + MutationObserver to this stuff, and why not some state change?

**Comment by chrishtr** [comment]
> I don't see where the asynchronous part comes from.
> (Smooth scrolling can be async. )

Exactly, this is async. Ultimately the spec even says it can be instant or smooth, depending.

> And the issue applies to other cases too, like window.find();

This one is apparently not even spec'ed.

> What is the reason to use DOM attribute + MutationObserver to this stuff, and why not some state change?

Where would this magic state live, and how would the developer set it?

The developer and UA can both control the `rendersubtree` state. In cases where activation is desired, the UA needs to be able to change state set by the developer. This is why it is on an attribute.

**Comment by smaug----** [comment]
> Exactly, this is async. Ultimately the spec even says it can be instant or smooth, depending.

But instant isn't async. It is supposed to happen, well, instantly. Where does the spec say something like queue a task to do 'foo'.

> Where would this magic state live, and how would the developer set it?

The state would be an internal slot on the element. In some sense rendersubtree is a bit like document's ready state.

https://html.spec.whatwg.org/#htmldetailselement does use open attribute in this similar a bit unexpected way, but at least it dispatches a separate event 'toggle' explicitly and doesn't rely on MutationObserver

**Comment by chrishtr** [comment]
> But instant isn't async. It is supposed to happen, well, instantly. Where does the spec say something like queue a task to do 'foo'.

Instant isn't instant - rendering steps take time to be scheduled.

But stepping back: the point is to allow the developer to participate in updating the rendering before pixels actually appear to the user. Do you agree with that goal?


> The state would be an internal slot on the element. In some sense rendersubtree is a bit like document's ready state.

That approach has the downside that it requires script for developers to boot up, which makes it very difficult to use during load. Attributes have a serialized HTML form, which allows them to participate in page load very easily.

The original API shape proposed and implemented was a lot like what your suggestion sounds like. We changed to attributes for simplicity and to support all the use cases like load in which script is hard to insert.

**Comment by smaug----** [comment]
> Instant isn't instant - rendering steps take time to be scheduled.

ok, so the current draft for that doesn't then explain at all what the processing model is supposed to be. Currently it says about activate
" it must run the following steps before the next time the update the rendering steps run, any user input is processed that may target the element, or any algorithm may consume data about that element:"
And many APIs sure may consume data about the element, like if one uses instant scrollIntoView() and then uses some other API to check the current scroll information.
We can't run microtasks checkpoint at any time when "any algorithm may consume data about that element"

**Comment by chrishtr** [comment]
> And I do understand why you want to notify about state change (whether it is dom attribute change or some other state change), it is the explicit microtask checkpoint which is causing problems.

Ok. If it isn't a microtask checkpoint, then there needs to be some other point before the rendering steps at which it's safe to notify script that an activate is about to happen. As you mentioned, this has to be on the event loop and not nested within a user agent algorithm.

Another option is to specify that an event be fired at the start of the update-the-rendering steps, at a similar/same timing as `requestAnimationFrame` callbacks. That would also work I think. Do you agree?

**Comment by smaug----** [comment]
> As you mentioned, this has to be on the event loop and not nested within a user agent algorithm.

Ok, this is not clear from the current draft, since it explicitly wants to 'activate' while other algorithms are running. Is that not the case anymore?
" it must run the following steps before ...  any algorithm may consume data about that element:"

Do we now only want to run the activate steps when rendering steps are about to be run?

In theory running an explicit microtask checkpoint before at the beginning of rendering steps if possible, since that wouldn't break anything. It could be treated as a separate task happening right before rendering. A bit ugly conceptually, since microtasks really should be processed. end-of-outermost-script-execution-or-end-of-task.
So, firing an explicit event during rendering steps sounds better to me.
(but I'm now lost with requirements. The draft wants to run activate steps also outside rendering steps, but you're hinting only rendering steps is needed.)

**Comment by chrishtr** [comment]
> So, firing an explicit event during rendering steps sounds better to me.

Ok, great. (I appreciate your help so far working through this issue.)

> (but I'm now lost with requirements. The draft wants to run activate steps also outside rendering steps, but you're hinting only rendering steps is needed.)

The requirement is simply that script be able to respond to activation (by doing its own mutations to DOM or other state) before the browser updates style, layout and paint, and commits pixels to the screen, so that everything looks good in the next visual update. Any time at the beginning of the rendering steps or earlier would be potentially fine.

The current  proposed spec text was an attempt to do that via microtasks.

**Comment by vmpstr** [comment]
Closing this for now. We're working on the `beforematch` event and we're incorporating a lot of the decisions made here into the new event. In particular, we're hoping to fire this at render timing instead of in the middle of script.  There are some problems, specifically things like #135 that still need to be addressed, but we're working towards solving that.
