### ISSUE TITLE
rendersubtree attribute values.

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#68]
We're thinking of using tokens to allow more things to be stopped. for example:

rendersubtree="visible"
rendersubtree="invisible"
rendersubtree="invisible activatable"
rendersubtree="invisible activatable holdupgrades"
rendersubtree="invisible activatable holdupgrades lazyload"

We need to spec/document this and enumerate the "starting set" of things that should be supported, vs discussed later.

**Comment by chrishtr** [comment]
One question: what happens if we get:

rendersubtree="invisible visible"

Should "visible" override "invisible" because it's later? I think probably yes.

A second question: should "holdupgrades" or other values imply "invisible"? I think no.

**Comment by chrishtr** [comment]
Also, what should "activatable" mean in this syntax? I propose it means that, if present anywhere
in the list of tokens, the browser has permission to remove all of them and replace the attribute
with "visible".

**Comment by chrishtr** [comment]
Another question: what does "invisible activatable holdupgrades mean"?

Does it mean that the user agent can't look inside of shadow DOM? I think the answer should be no.

It just means that until "holdupgrades" is removed, custom element upgrades are paused.

**Comment by vmpstr** [comment]
> Should "visible" override "invisible" because it's later? I think probably yes.

I agree. I think in incompatible token scenarios, the latter ones should override the former ones.

> A second question: should "holdupgrades" or other values imply "invisible"? I think no.

That's interesting. I don't have a strong feeling about this, so I'm fine with the ability to holdupgrades without being invisible. It raises a question of what to do if we have "activatable holdupgrades", since it's visible, so do we still need to process it for activatability in order to resume upgrades?

> Also, what should "activatable" mean in this syntax? I propose it means that, if present anywhere
> in the list of tokens, the browser has permission to remove all of them and replace the attribute
> with "visible".

I think this makes sense. I think this is a departure from our prototype that only considers activatability in cases when the element is invisible.

> Another question: what does "invisible activatable holdupgrades mean"?
> 
> Does it mean that the user agent can't look inside of shadow DOM? I think the answer should be no.
> 
> It just means that until "holdupgrades" is removed, custom element upgrades are paused.

My lack of knowledge is going to show, but isn't the act of upgrading can construct the shadow DOM? Ie, what is the objective of looking inside the shadow DOM if it can change on upgrade?

/cc @domenic

**Comment by vmpstr** [comment]
It also occurs to me that in a somewhat contrived way, we could have attribute values that eliminate the need for updateRendering, such as:

dev setting
rendersubtree="invisible" -> rendersubtree="make_visible_without_janking" 
then UA setting
rendersubtree="make_visible_without_janking" -> rendersubtree="visible"

Or something like 
dev setting
rendersubtree="invisible" -> rendersubtree="invisible please_update_rendering" 
then UA setting
rendersubtree="invisible please_update_rendering" -> rendersubtree="invisible" 

with all of the changes being observed by mutation observer, this is equivalent to updateRendering, right?

**Comment by domenic** [comment]
> Should "visible" override "invisible" because it's later? I think probably yes.

In general token lists attributes are treated as unordered, although they are technically ordered. This allows authors to treat them in an unordered way. So I think it the order should not matter; you should define what `rendersubtree="invisible visible"` does.

I wonder if it's possible to come up with a scheme where `rendersubtree=""` (with no tokens) replaces having to explicitly state "visible". That seems more elegant, as then it's impossible to get into the contradictory state of having both tokens present.

> My lack of knowledge is going to show, but isn't the act of upgrading can construct the shadow DOM? Ie, what is the objective of looking inside the shadow DOM if it can change on upgrade?

Upgrading can run arbitrary code. Such code can, and often does, add shadow DOM to the element.

But in my opinion I think shadow DOM should be orthogonal to this entire feature. There should be no interaction.

**Comment by vmpstr** [comment]
> But in my opinion I think shadow DOM should be orthogonal to this entire feature. There should be no interaction.

Do you think #32 is a reasonable concern which we should mention in the spec? Ie whether locking has a flat-tree vs light dom effect

**Comment by domenic** [comment]
Fair, yes, any part of the spec which specifies "descendant" needs to state exactly how those descendants are calculated.

**Comment by chrishtr** [comment]
> I think this makes sense. I think this is a departure from our prototype that only considers activatability in cases when the element is invisible.

Good point. After reading this, at first I was going to change my mind and say it should only be if invisible, but it seems it's a good idea for the UA to modify rendersubtree="holdupgrades" to rendersubtree="visible" and thereby allow those upgrades to happen before finishing the UA feature's algorithm.

> I wonder if it's possible to come up with a scheme where `rendersubtree=""` (with no tokens) replaces having to explicitly state "visible". That seems more elegant, as then it's impossible to get into the contradictory state of having both tokens present.

I like this idea, and it seems workable. The rendersubtree attribute would then control four independent bits:
* invisibility to paint & hit testing
* custom element upgrades 
* network fetches
* whether it's ok for the UA to turn off the other bits when running its features' algorithms

Each bit has one keyword, and the order doesn't matter.

The question then may be raised: why aren't there four attributes? I guess there could be, but since "activatable" is intended to kill off the other three when it is used by the UA, it seems logical to have them on one combined attribute. However, it would be feasible as well to have four different attributes: `invisible` `activatable` `holdupgrades` `lazyload`.

**Comment by domenic** [comment]
> The question then may be raised: why aren't there four attributes? I guess there could be, but since "activatable" is intended to kill off the other three when it is used by the UA, it seems logical to have them on one combined attribute. However, it would be feasible as well to have four different attributes: invisible activatable holdupgrades lazyload.

I agree both could work. It feels more "economical" to have a single attribute, but I can be persuaded either way. I'd say go with a single attribute for now, but be prepared to change based on input?

Although, one that gives me pause is lazyload. We already have that on img and iframe. It seems very reasonable to extend that to every element, where it means "my inclusive-descendant img and iframe elements get lazy loaded". So maybe that one in particular might peel off into its own attribute...

**Comment by chrishtr** [comment]
https://github.com/whatwg/html/issues/4861

**Comment by vmpstr** [comment]
Obsolete
