### ISSUE TITLE
Searchable dom interactions

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#7]
Investigate if display locking can be used for searchable, but invisible, dom

**Comment by chrishtr** [comment]
See https://github.com/rakina/searchable-invisible-dom/blob/master/README.md for reference.

One proposal:

Marking an element as invisible  => getDisplayLock().acquire();

Marking an element as visible => getDisplayLock().update(() => getDisplayLock().commit());

activateinvisible event => listen for beforecommit event (#36) on the DisplayLockContext. In the handler for this event, un-invisible other nearby elements which are related to the one being activated by calling
getDisplayLock().commit() on them. They will all commit together.
