### ISSUE TITLE
Effect of 'skipped' values on canvas elements

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#70]
Canvas is painted via script outside of the regular rendering pipeline. I added the following sentence to the draft PR, for what happens when rendersubtree=invisible:

*The <span>WebGLRenderingContext</span> for a <span data-x="concept-canvas-webgl">webgl</span>-backed canvas element may be lost.*

**Comment by vmpstr** [comment]
We need to see what happens here with the css version.

**Comment by vmpstr** [comment]
Presumably, the canvas paints itself which includes all of the contents drawn by script, so I think we're fine here. However, we should definitely write some tests for this.
