### ISSUE TITLE
Setting visibility via CSS?

### ISSUE THREAD

**Issue by chrishtr** [WICG/display-locking#89]
Maybe instead of setting visibility via attribute mutation, it could be set via an internal state of the element, via [how we plan to expose them for custom elements](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/custom-states-and-state-pseudo-class.md) and a :visible pseudo class that allows styling based on the state.

Then rendersubtree could become a CSS property and not an attribute.

**Comment by rakina** [comment]
I don't quite understand, since ElementInternals is only exposed on custom
elements, does this mean we only want this for custom elements?

**Comment by chrishtr** [comment]
No, not only for custom elements. I was riffing on the possible APIs; perhaps we would need a new solution to set and query the bits. Maybe that would just be new methods:

`Element.setVisible()`
`Element.setInvisible()`
`element.isVisible()`

**Comment by rakina** [comment]
That sounds quite similar to the imperative API we moved away from. I think
one of the reasons we wanted the declarative version is because we don't
need script.

**Comment by chrishtr** [comment]
I don't think script would be necessary. If you put:

`<div style="render-subtree: invisible"></div>`

and activation was the default, then the element would be rendered whenever it became visible in the viewport. Likewise via a user agent API.

**Comment by chrishtr** [comment]
I think the key difference from our prior thinking is that we now have viewport activation built-in.

**Comment by fergald** [comment]
I'm not sure what your goal is. Are you trying to eliminate the attribute
or just exploring more ideas? What difference does it make if we have a
HTML attribute vs a JS attribute?

This made me wonder, how about having an `in-viewport` CSS selector, then
there's no magic, just style (4 words I try to live my life by :) and we
have added a new primitive to the platform. It may need to come with a
bunch of restrictions on what elements it can select but now visibility is
just a computed style, not a special bit and maybe something similar works
for FIP, selection and tab navigation etc.

>

**Comment by chrishtr** [comment]
The goal is to be able to use CSS to set rendersubtree, because it is more convenient to work with.

**Comment by fergald** [comment]
OK, then an `in-viewport` selector fits perfectly with that. That would
remove the weirdness of CSS saying "invisible" with reality being "visible".

**Comment by chrishtr** [comment]
Summary then: 

1. A `rendersubtree` CSS property, whose tokens are the same ones we know and love from the current implementation. 
2. An internal Element state of `rendersubtree`
3. A `::subtreerendered` pseudoclass to reflect this state
4. A `setRenderingSubtree()` method on Element that takes a boolean parameter and sets `rendersubtree` accordingly
5. An `isRenderingSubtree()` method on Element
6. A `beforeactivate` event when `rendersubtree` has been set to true
7. The UA can set the `rendersubtree` state to true according to the rules in #87. It never sets it to false.

Feel free to bikeshed these names...

**Comment by chrishtr** [comment]
The previous comment summarizes how I think it would work if `rendersubtree` was a CSS property. This is similar to focus, which has a `::focus` pseudoclass, a `focus()` method and an `onfocus` event.

I don't think there is an `isFocused()` method though.

**Comment by fergald** [comment]
I'm not sure if the analogy to focus is correct or if it is, maybe the
naming is confusing me. The `::focus` pseudoclass selects an element that
is focused and allows you to apply style to it. The `::subtreerendered`
pseudo-class seems to be seelcting on what the eventual computed visibility
is but I'm not sure/ Would it select an element on which I manually called
`setRenderingSubtree(true)` or would it select an element that the browser
felt should be activated regardless of whether I overrode that? What would
I use this selector for? Why would I ever want to style things differently
when they are rendered vs unrendered (given that unrendered is
invisible and has no style cost)?

**Comment by chrishtr** [comment]
It would select an element that had `rendersubtree` equal to true, meaning the subtree renders. (I agree the naming needs work.)

I'm not sure what it would be used for. The UA could use it to override rendering with a UA rule such as:

```
*::subtreerendered !important {
  rendersubtree: ''
}
```

Maybe this would be a good way to explain the magic.

**Comment by vmpstr** [comment]
Let me try to come up with an example to see if I understand this correctly:
```html
<style>
.foo {
  rendersubtree: invisible;
}
.bar {
  rendersubtree: invisible skip-viewport-activations;
}
</style>
<div class=foo>Hello</div>
<div class=foo>Hi</div>
<div class=bar>Goodbye</div>
<div class=bar>Farewell</div>
<div class=unrelated>Giraffes</div>
```

Now, if either Hello or Hi are in the viewport, then we get a `beforeactivate` and the internally it gains a `::subtreerendered` pseudoclass which UA makes visible. for Goodbye and Farewell this doesn't happen, but if it's found by find-in-page they it does gain the `subtreerendered`.

The question I have is how does the developer clear this? `setRenderingSubtree(false)` clears the `subtreerendered`. Meaning that if it's called on .foo or .bar elements, they again become invisible. 

What happens if I call `unrelated.setRenderingSubtree(false)`? Or what happens if I call `unrelated.setRenderingSubtree(true)`? Does it just affect the pseudoelement's presence and nothing else? Ie, `unrelated.setRenderingSubtree(false)` has no effect and `true` means that we get `rendersubtree: ''`?

**Comment by chrishtr** [comment]
Possible answers:

For elements that don't specify a `rendersubtree` property (`unrelated` in your example), calling `setRenderingSubtree` would have no effect.

If the developer calls `setRenderingSubtree(false)` then come back on due to visibility in the viewport. I think the current implementation has this problem and we haven't solved it yet; is there something you can see that is specific to the CSS property version of the API?

Alternatively, maybe the developer can't set the pseudoclass state at all. If the developers wants to do the equivalent thing  they could just cause a style change that changes `rendersubtree`.

**Comment by fergald** [comment]
I'm confused by the purpose of this pseudoclass, I can't think of any
reason to ever use it as a selector. The interaction between manual setting
of `setRenderingSubtree` and the selectors is also unclear to me and it
seems odd that setting it to false only has an effect if there is a
`rendersubtree` property being applied to that element.

Here's what I was thinking of

```html

<style>
.foo, .bar {
  rendersubtree: invisible;
}
.foo::activated {
  rendersubtree: invisible
}
</style>
<div class=foo>Hello</div>
<div class=foo>Hi</div>
<div class=bar>Goodbye</div>
<div class=bar>Farewell</div>

<div class=unrelated>Giraffes</div>
```

The browser effectively applies a style to default activate:

```css
*::activated {
  rendersubtree: visible
}
```

There's no attribute at all (you can look at the computed style to find out
if something has rendersubtree), there's no `::rendersubtree` pseudoclass
and maybe `::activated` can take parameters if you'd like to control
exactly what type of activation you're talking about.

**Comment by chrishtr** [comment]
> There's no attribute at all (you can look at the computed style to find out if something has rendersubtree), there's no `::rendersubtree` pseudoclass and maybe `::activated` can take parameters if you'd like to control exactly what type of activation you're talking about.

There is a pseudoclass (i.e. `activated`), but point taken.

However, I think there is a need for script to set activated to false, for e.g. the virtual-scroller use case.

Otherwise I think what you wrote is looking reasonable.

**Comment by fergald** [comment]
> > There's no attribute at all (you can look at the computed style to find out if something has rendersubtree), there's no `::rendersubtree` pseudoclass and maybe `::activated` can take parameters if you'd like to control exactly what type of activation you're talking about.
> 
> There is a pseudoclass (i.e. `activated`), but point taken.

To be clear, what I mean is that there's a pseudoclass that is actively used and might be generally useful in ways we haven't thought about.

> However, I think there is a need for script to set activated to false, for e.g. the virtual-scroller use case.

I think a virtual scroller would do something like

```html
<style>
  my-elements::activated(viewport) { rendersubtree: invisible }
</style>
```

then it could just flip the style directly on the elements it wants to make visible (or use another rule to select them in some other way, e.g. a class that it applies to elements that should be visible).

> Otherwise I think what you wrote is looking reasonable.

**Comment by chrishtr** [comment]
> then it could just flip the style directly on the elements it wants to make visible (or use another rule to select them in some other way, e.g. a class that it applies to elements that should be visible).

What about elements that are activated via find-in-page? Don't you want to re-lock them if they move off the viewport?

**Comment by fergald** [comment]
> What about elements that are activated via find-in-page? Don't you want to re-lock them if they move off the viewport?

Good question. I guess that could depend on why they were hidden to start with.

In my description, everything locks itself again once it stops being activated. Maybe that's a fatal flaw with my one because I don't really see a way for activation to stick unless it is defined to be sticky and there's an `activated` bit that elements carry around. I'm not super keen on that but having that and being able to clear it (with the possibility that the UA could immediately set it back on again) it might still be clearer semantics than the `setRenderingSubtree` version.

**Comment by rakina** [comment]
From the discussions above, is this what we want?
* An internal state that determines whether an element's subtree is rendered, controlled by the UA.
* A way for authors to change the the internal state, via script.
* A way for authors to ask for an element's subtree to not get rendered, via css. (will not change the UA internal state if it says things should be rendered)
* A way for authors to know whether an element's subtree is actually rendered or not.

I don't think we can just move the attribute version's values as is to be the internal state/css property values. As the interactions here are quite complicated than the attribute version.

Let me propose the CSS property to be named something like `subtree-render-request`, with values `skip [no-viewport-activation] [no-activation]` (skips rendering if internal state allows) and `render` (default value, renders it).

The internal subtree rendering states will be:
* allow skipping (if `subtree-render` is `skip-if-possible`, will skip rendering subtree)
* forbid skipping, must render (doesn't care about `subtree-render` value, will render subtree)

Activation will change the internal state. When an element gets activated, its internal state will change to "must render", and will stay that way until it's changed by the function below. In the spec we probably would explain that "forbid skipping" makes the element match a UA !important rule that sets `subtree-render-request` to `render`.

The authors can then call a function on element to  change the internal state.
```js
el.setSubtreeRenderSkip("allow-skip");
el.setSubtreeRenderSkip("forbid-skip");
```
Note that if viewport activation is active the element can immediately/in the next frame get activated again and the internal state will change back.

If it's awkward to not have a way to set subtree render skipping through script (the functions above only allows/forbid following the CSS property), then maybe we should add other internal states.
* must skip rendering, activatable
* must skip rendering, not activatable
* must skip rendering, activatable no-viewport-activation

Like "forbid skipping", "must skip rendering" makes the element match a UA !important rule that sets `subtree-render-request` to `skip` (plus additional activatability stuff)

and now we can do
```js
el.setSubtreeRenderSkip("must-skip no-activation");
el.setSubtreeRenderSkip("must-skip no-viewport-activation");
el.setSubtreeRenderSkip("must-skip no-activation");
```
or something like that.

Finally we have `el.isSubtreeRenderingSkipped()` to know whether the rendering is actually skipped or not. Maybe a pseudo class version is useful too? Not sure.

**Comment by rakina** [comment]
@fergald suggested that we might want two internal states "activated/not" and "render/skip", and the JS API can only set the "activated/not" state. The "render/skip" internal state would be affected by the CSS rendersubtree value, and the "activated/not" state. The UA can change the "not activated" state to "activated".

With those, I think we can emulate the attribute version:

```html
<style>
[rendersubtree="invisible"] {
  rendersubtree: "invisible";
}
[rendersubtree=""] {
 rendersubtree: "";
}
</style>
<div rendersubtree="invisible"></div>

<script>
div.onbeforeactivate = () => {
  div.setAttribute("rendersubtree", "");
}

// When locking, need to set element to "not activated" to guarantee that the CSS value is used.
div.setAttribute("rendersubtree", "invisible");
div.setRenderSubtreeActivated(false);
// Note that in the next frame (or immediately?) the UA chan change the div's activated state back to "activated" again.
</script>
```

I kinda like this because it's simpler, and web authors can just use their favorite way to modify the rendersubtree property (using an attribute like above, or a .class, or modify style attribute directly). Also maybe we need additional pseudoclasses/functions to check the actual value of "rendered/not".

**Comment by vmpstr** [comment]
There are a few more cases that I think are worth talking about. First, the containment on rendersubtree="" is still present. It's unclear how to make this present in CSS? Is
`rendersubtree: ""` a thing we would ask devs to put in style if they are planning on changing rendersubtree to something like invisible? That would prevent the change in layout due to new containment.

The other case I'm somewhat confused about is the internal state (whether or not it's exposed by a pseudoclass). For example,

I put a rendersubtree: invisible css class c on an element e. Then I do find in page that activates e. Then I remove class c from e. Then I add the class again. Now, at this point is e's subtree rendered? Ie, the internal state would have it as activated and nothing explicitly cleared that state, other than clearing the class that had the rendersubtree. I don't know what the right answer is, but it seems that we should hide the subtree in this case.

Similar case is if I have a class that puts rendersubtree: "" on an element. Would it have the internal state and react to activations (with beforeactivate signals)?

**Comment by chrishtr** [comment]
> First, the containment on rendersubtree="" is still present. It's unclear how to make this present in CSS?

Or we could add a `will-change: rendersubtree`. `will-change` is how we solved the analogous problem with other expensive properties.

> I put a rendersubtree: invisible css class c on an element e. Then I do find in page that activates e. Then I remove class c from e. Then I add the class again. Now, at this point is e's subtree rendered?

Yes, because activation overrides `rendersubtree`. in other words, here is the pseudocode for whether an element's subtree should render:

```
Element::ShouldRenderSubtree() {
  if (AmIActivated())
    return true;
  if (DoIHaveTheRenderSubtreeInvisibleToken())
    return false;
  return true;
}
```

This is why Rakina put this line in her example:

```
div.setRenderSubtreeActivated(false);
```

**Comment by chrishtr** [comment]
Also, I think activation has to be triggered by a first `rendersubtree`. Explanation:

Suppose we extend activation to be a concept totally divorced from the rest, which relates to whether an element is being rendered at all. If we decide to render an element it is activated unless prevented by the rendersubtree rules. Then `Element::ShouldRenderSubtree` would be:

```
Element::ShouldRenderSubtree() {
  return AmIActivated();
}
```

and the UA would be expected to set the bit to true whenever it got around to rendering the element.
However, race conditions / exposing details of when rendering occurs may result from this decision, requiring script to solve.

Consider:

1. UA starts loading page
2. UA gets around to rendering the element
3. CSS loads which sets `rendersubtree:invisible`

vs

1. UA starts loading page
2. CSS loads which sets `rendersubtree:invisible`
3. UA gets around to rendering the element

If activation was only a thing that happened when `rendersubtree` was already set, then the two examples would behave the same. If activation was independent of `rendersubtree` then the first would render but not the second.

The developer would then have to add script to force off activation for all elements on bootup, which is pretty bad. For this reason, activation has to be connected to `rendersubtree` already being set.

**Comment by chrishtr** [comment]
Rakina your last proposal excites me a lot, because it seems we can implement it and then throw the polyfill into our existing demos without change!

**Comment by vmpstr** [comment]
The proposal sounds good. The only thing that concerns me is that if we have something like a virtual scroller that keeps track of its own visibility (ie no viewport activations), then it might not occur to me as a developer to clear the activated state unconditionally, mostly because everything seems to work just fine (performance is good when I test it because I didn't test activations; in prod no visual bugs because I only lock offscreen elements and although they don't lock if they were activated, I can't tell since they are offscreen). It's just a bit subtle. 

I guess this would also be true with viewport activations. It's pretty hard to tell that I forgot to clear this state. 

My concern here is purely ergonomics, btw, since I think from the behavior point of view this achieves everything we want.

**Comment by vmpstr** [comment]
Note that the difference is that in our attribute version the only want this interaction happens is if UA is _actively_ fighting the dev by activating as soon as it's invisible. 

In the proposed version, this interaction happens if _sometime in the past_ the element was activated (and the developer didn't clear the state)

**Comment by chrishtr** [comment]
I agree with you that the ergonomics are slightly more subtle. However it is as simple as telling developers

* Use the CSS to indicate rendering constraints regarding default invisibility and activation
* Call `setRenderSubtreeActivated(false)` and indicate invisibility to cause not-rendered
* Use `will-change: rendersubtree` on all elements which might receive rendersubtree in the future

> (performance is good when I test it because I didn't test activations;

Isn't this a potential problem of any version? If you don't test activations and re-lock, you'll get bad performance sometimes.

>  in prod no visual bugs because I only lock offscreen elements and although they don't lock if they were activated, I can't tell since they are offscreen)

This is only a failure mode if "I only lock offscreen elements" means "set the rendersubtree CSS property", which is definitely a wrong application of the API. But I see your point here - it will sometimes work and sometimes not.

This will be made slightly worse by the requirement to ignore any activations before the first time `rendersubtree` is applied. (See my previous comment.)

**Comment by flackr** [comment]
If I understand correctly, if activation only happens when rendersubtree is set, then setting rendersubtree: <initial-value> should remove activation, right? I assume this means the initial value is not the same as the `rendered` value set when activated?

**Comment by vmpstr** [comment]
I think that's the only remaining question in my mind. Specifically, what's the lifetime of the activated internal state. I agree with @chrishtr  that it should only start to exist when rendersubtree is set. 

However, I kind of feel like we should clear the state if we clear rendersubtree altogether. Then, on the next application of the class that sets it, it makes it invisible by initializing the activated state again (to false).

So the path to making it invisible would be either:
1. Clear the rendersubtree state and set it again
2. Clear the internal activated state via JS api

I think this allows the following type of pattern:
```html
* {
  will-change: rendersubtree
}
.hidden {
  rendersubtree: invisible;
}

// show
e.onbeforeactivate = () => { e.classList.remove('hidden'); };

// hide
e.classList.add('hidden');
```

in addition to the pattern that @rakina already mentioned.

**Comment by chrishtr** [comment]
I think maybe we can define "clear" to mean removing "invisible" from the token list.

Elements with `rendersubtree` other than including `invisible` are always activated. (and therefore the `::active` pseudoclass always matches). When `rendersubtree` is first set to invisible, the element becomes not-activated, until an activation-inducing event occurs.

This would mean that an element may become not-activated during the rendering update steps (style application phase in particular). This in turn means that `contain:size` may start applying to an element at that time.

`contain:size` also depends on activation state in general in this new design. I think this is ok because nothing in the document lifecycle should be able to change it. In particular, viewport activation should apply to the next render, not the current one.

**Comment by chrishtr** [comment]
Here is a work-in-progress doc writing up a complete solution to a CSS version:

https://docs.google.com/document/d/17j84ibHbQR21evUPJNSeCjvbm0pSSo-cWPiUjqszRt8/edit#

Let's discuss there final details, as it's easier to make small edits in docs rather than a Github thread.

**Comment by vmpstr** [comment]
We did this probably.
