### ISSUE TITLE
activation signal naming bikeshed

### ISSUE THREAD

**Issue by vmpstr** [WICG/display-locking#98]
We have agreed in the last discussion to fire the signal at approximately raf timing (before the callbacks), and if the raf callback causes an activation, then it will be delayed until the next animation frame.

Given this, `beforeactivate` is a bit of a misnomer, since it implies that the event is fired before we activate the element. The reality is the following:

1. If an element is activated by one of the following, then the event fires before the next lifecycle is updated and the activated element's subtree becomes visible.
    1. user action (find-in-page, tab navigation, etc)
    1. script running outside of an animation frame
    1. script running as a result of steps 10.6, 10.7, and 10.9 of [update the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering)
    1. post animation frame timing script (including intersection observer callbacks)
1. If an element is activated by one of the following, then the frame that activates the element will be processed and the activated element's subtree will be rendered. The event signaling this activation will run at the next animation frame.
    1. rAF callbacks
    1. resize observer callbacks

The proposed timing for this event is rouhgly at 10.10 of https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering

In fact, reusing the same task queue (Chromium impl details here) is possible here, much in the same way it uses the same event queue for 10.6, 10.7, and 10.9

Because of the second point above, we should probably think of a different name for the event. I suggest `rendersubtreechanged` with spec language guaranteeing before-activation timing for the first point above

/cc @chrishtr @rakina for thoughts

**Comment by rakina** [comment]
probably `rendersubtreeactivation` is more accurate since we aren't going to fire the event on manual rendersubtree changes?

**Comment by chrishtr** [comment]
`rendersubtreeactivating` ?
